#!/usr/bin/env python3
"""
Motivatsiya matinlari
"""

MOTIVATSIYA = {
    "uz": [
        "🚀 Motivatsiya boshlashga yordam beradi, odat esa davom etishga.",
        "🚀 Biz nimaniki muntazam qilsak, o'shanga aylanib boramiz. Muvaffaqiyat bu tasodif emas, odatdir.",
        "🚀 Dastlab biz odatlarimizni shakllantiramiz, so'ngra odatlarimiz bizni.",
        "🚀 Har kungi 1 foizlik o'sish bir yildan so'ng 37 barobar kuchliroq bo'lishingizni ta'minlaydi.",
        "🚀 Muvaffaqiyat — bir martalik mo'jiza emas, har kungi kichik odatlar mahsulidir.",
        "🚀 Intizom motivatsiyadan kuchliroq. Kayfiyatga qarab emas, maqsadga qarab harakat qiling.",
        "🚀 Maqsadlaringiz darajasiga ko'tarilmaysiz, odatlaringiz darajasiga tushib qolasiz.",
        "🚀 Eng qiyini — birinchi qadamni tashlash. Shunchaki boshlang.",
        "🚀 Katta o'ylang, lekin juda kichik qadamdan boshlang.",
        "🚀 Ketma-ket ikki marta o'tkazib yubormang. Birinchi xato — tasodif, ikkinchisi — yomon odatning boshlanishi.",
        "🚀 Barqarorlik — har qanday muvaffaqiyatning asosiy kalitidir.",
        "🚀 Mukammallikka intilmang, doimiy o'sishga intiling.",
        "🚀 Yomon odatni shunchaki tashlab bo'lmaydi, uni yaxshisi bilan almashtirish kerak.",
        "🚀 Natijaga emas, o'sha natijaga munosib insonga aylanishingizga e'tibor bering.",
        "🚀 Odat — yengib o'tiladigan marra emas, yashash tarzidir.",
        "🚀 Hatto kayfiyatingiz yo'q kunlari ham, qoida uchun ozgina bo'lsa-da harakat qiling.",
        "🚀 Irodangizga tayanmang, atrof-muhitni o'z odatlaringizga moslashtiring.",
        "🚀 To'g'ri ishni bajarishni osonlashtiring, chalg'ituvchi narsalarni uzoqlashtiring.",
        "🚀 Kutib o'tirmang, harakat qilsangiz motivatsiya o'z-o'zidan keladi.",
        "🚀 Bugun qilgan harakatingiz butun kelajagingizni yaxshilashi mumkin.",
        "🚀 Vaqt yaxshi odatlarni do'stingizga, yomonlarini dushmaningizga aylantiradi.",
        "🚀 O'zingizga qilingan har kungi kichik sarmoya kelajakda eng katta foyda keltiradi.",
        "🚀 Buyuk ishlar bir kunda qilinmaydi, sabrli bo'ling.",
        "🚀 Zanjirni uzib qo'ymang: uzluksizlik natijani kafolatlaydi.",
        "🚀 Natijani ko'rmayotgan bo'lsangiz ham to'xtamang; ildiz doim tuproq ostida o'sadi.",
        "🚀 Sizning bugungi hayotingiz — o'tmishdagi odatlaringizning yig'indisi xolos.",
        "🚀 Ertalabki birinchi g'alaba (odat) butun kuningizni belgilab beradi.",
        "🚀 Qiyinchiliklar o'sish jarayonining bir qismidir, qochmang, yuzlaning.",
        "🚀 Qayd etilgan narsa o'sadi: odatlaringizni kuzatib boring.",
        "🚀 Siz bu ishlarni \"qilishga majbur emassiz\", balki \"qilish imkoniyatiga egasiz\".",
    ],
    "en": [
        "🚀 Motivation helps you start, but habit keeps you going.",
        "🚀 We become what we repeatedly do. Excellence is not an accident, it is a habit.",
        "🚀 First we shape our habits, then our habits shape us.",
        "🚀 A 1% daily improvement makes you 37 times stronger in a year.",
        "🚀 Success is not a one-time miracle, it is the product of daily small habits.",
        "🚀 Discipline is stronger than motivation. Act based on your goal, not your mood.",
        "🚀 You do not rise to the level of your goals, you fall to the level of your habits.",
        "🚀 The hardest part is taking the first step. Just start.",
        "🚀 Think big, but start with a tiny step.",
        "🚀 Never miss twice in a row. The first miss is an accident, the second is the start of a bad habit.",
        "🚀 Consistency is the key to any success.",
        "🚀 Do not strive for perfection, strive for constant growth.",
        "🚀 You cannot just quit a bad habit, you need to replace it with a better one.",
        "🚀 Focus not on the result, but on becoming the person worthy of that result.",
        "🚀 A habit is not a finish line to cross, it is a way of life.",
        "🚀 Even on days when you feel low, do at least a little to keep the rule.",
        "🚀 Do not rely on willpower, adapt your environment to your habits.",
        "🚀 Make the right thing easy to do, and distractions hard to reach.",
        "🚀 Do not wait for motivation, start acting and it will come.",
        "🚀 What you do today can improve your entire future.",
        "🚀 Time turns good habits into your friend and bad ones into your enemy.",
        "🚀 Every small daily investment in yourself brings the greatest return in the future.",
        "🚀 Great things are not done in a day, be patient.",
        "🚀 Do not break the chain: consistency guarantees results.",
        "🚀 Even if you do not see results yet, keep going. Roots always grow underground.",
        "🚀 Your life today is simply the sum of your past habits.",
        "🚀 Your first morning victory (habit) sets the tone for your entire day.",
        "🚀 Challenges are part of the growth process. Do not run, face them.",
        "🚀 What gets tracked gets improved: keep monitoring your habits.",
        "🚀 You do not have to do this, you get to do this.",
    ],
    "ru": [
        "🚀 Мотивация помогает начать, а привычка помогает продолжать.",
        "🚀 Мы становимся тем, что делаем регулярно. Успех — не случайность, а привычка.",
        "🚀 Сначала мы формируем привычки, а потом привычки формируют нас.",
        "🚀 Ежедневный рост на 1% за год сделает тебя в 37 раз сильнее.",
        "🚀 Успех — не разовое чудо, а результат ежедневных маленьких привычек.",
        "🚀 Дисциплина сильнее мотивации. Действуй ради цели, а не по настроению.",
        "🚀 Ты не поднимаешься до уровня целей, а опускаешься до уровня привычек.",
        "🚀 Самое сложное — сделать первый шаг. Просто начни.",
        "🚀 Думай масштабно, но начинай с крошечного шага.",
        "🚀 Не пропускай дважды подряд. Первый пропуск — случайность, второй — начало плохой привычки.",
        "🚀 Постоянство — ключ к любому успеху.",
        "🚀 Не стремись к совершенству, стремись к постоянному росту.",
        "🚀 Плохую привычку нельзя просто бросить, её нужно заменить хорошей.",
        "🚀 Фокусируйся не на результате, а на том, чтобы стать достойным этого результата.",
        "🚀 Привычка — это не финиш, а образ жизни.",
        "🚀 Даже в плохие дни делай хотя бы немного, чтобы сохранить правило.",
        "🚀 Не полагайся на силу воли, адаптируй среду под свои привычки.",
        "🚀 Сделай правильное действие лёгким, а отвлекающее — трудным.",
        "🚀 Не жди мотивацию, начни действовать — она придёт сама.",
        "🚀 То, что ты делаешь сегодня, может улучшить всё твоё будущее.",
        "🚀 Время превращает хорошие привычки в друга, а плохие — во врага.",
        "🚀 Каждая маленькая ежедневная инвестиция в себя даёт самую большую отдачу.",
        "🚀 Великие дела не делаются за один день, будь терпелив.",
        "🚀 Не разрывай цепочку: непрерывность гарантирует результат.",
        "🚀 Даже если не видишь результат, не останавливайся. Корни всегда растут под землёй.",
        "🚀 Твоя сегодняшняя жизнь — это просто сумма прошлых привычек.",
        "🚀 Первая утренняя победа (привычка) задаёт тон всему дню.",
        "🚀 Трудности — часть роста. Не убегай, встречай их лицом.",
        "🚀 То, что отслеживается — улучшается. Следи за своими привычками.",
        "🚀 Ты не обязан это делать — у тебя есть возможность это делать.",
    ],
}

