#!/usr/bin/env python3
"""
Motivatsiya matinlari
"""

MOTIVATSIYA = {
    "uz": [
        "🚀 Siz qila olasiz! Motivatsiya boshlashga yordam beradi, odat esa davom etishga.",
        "🚀 Siz qila olasiz! Biz nimaniki muntazam qilsak, o'shanga aylanib boramiz. Muvaffaqiyat bu tasodif emas, odatdir.",
        "🚀 Siz qila olasiz! Dastlab biz odatlarimizni shakllantiramiz, so'ngra odatlarimiz bizni.",
        "🚀 Siz qila olasiz! Har kungi 1 foizlik o'sish bir yildan so'ng 37 barobar kuchliroq bo'lishingizni ta'minlaydi.",
        "🚀 Siz qila olasiz! Muvaffaqiyat — bir martalik mo'jiza emas, har kungi kichik odatlar mahsulidir.",
        "🚀 Siz qila olasiz! Intizom motivatsiyadan kuchliroq. Kayfiyatga qarab emas, maqsadga qarab harakat qiling.",
        "🚀 Siz qila olasiz! Maqsadlaringiz darajasiga ko'tarilmaysiz, odatlaringiz darajasiga tushib qolasiz.",
        "🚀 Siz qila olasiz! Eng qiyini — birinchi qadamni tashlash. Shunchaki boshlang.",
        "🚀 Siz qila olasiz! Katta o'ylang, lekin juda kichik qadamdan boshlang.",
        "🚀 Siz qila olasiz! Ketma-ket ikki marta o'tkazib yubormang. Birinchi xato — tasodif, ikkinchisi — yomon odatning boshlanishi.",
        "🚀 Siz qila olasiz! Barqarorlik — har qanday muvaffaqiyatning asosiy kalitidir.",
        "🚀 Siz qila olasiz! Mukammallikka intilmang, doimiy o'sishga intiling.",
        "🚀 Siz qila olasiz! Yomon odatni shunchaki tashlab bo'lmaydi, uni yaxshisi bilan almashtirish kerak.",
        "🚀 Siz qila olasiz! Natijaga emas, o'sha natijaga munosib insonga aylanishingizga e'tibor bering.",
        "🚀 Siz qila olasiz! Odat — yengib o'tiladigan marra emas, yashash tarzidir.",
        "🚀 Siz qila olasiz! Hatto kayfiyatingiz yo'q kunlari ham, qoida uchun ozgina bo'lsa-da harakat qiling.",
        "🚀 Siz qila olasiz! Irodangizga tayanmang, atrof-muhitni o'z odatlaringizga moslashtiring.",
        "🚀 Siz qila olasiz! To'g'ri ishni bajarishni osonlashtiring, chalg'ituvchi narsalarni uzoqlashtiring.",
        "🚀 Siz qila olasiz! Kutib o'tirmang, harakat qilsangiz motivatsiya o'z-o'zidan keladi.",
        "🚀 Siz qila olasiz! Bugun qilgan harakatingiz butun kelajagingizni yaxshilashi mumkin.",
        "🚀 Siz qila olasiz! Vaqt yaxshi odatlarni do'stingizga, yomonlarini dushmaningizga aylantiradi.",
        "🚀 Siz qila olasiz! O'zingizga qilingan har kungi kichik sarmoya kelajakda eng katta foyda keltiradi.",
        "🚀 Siz qila olasiz! Buyuk ishlar bir kunda qilinmaydi, sabrli bo'ling.",
        "🚀 Siz qila olasiz! Zanjirni uzib qo'ymang: uzluksizlik natijani kafolatlaydi.",
        "🚀 Siz qila olasiz! Natijani ko'rmayotgan bo'lsangiz ham to'xtamang; ildiz doim tuproq ostida o'sadi.",
        "🚀 Siz qila olasiz! Sizning bugungi hayotingiz — o'tmishdagi odatlaringizning yig'indisi xolos.",
        "🚀 Siz qila olasiz! Ertalabki birinchi g'alaba (odat) butun kuningizni belgilab beradi.",
        "🚀 Siz qila olasiz! Qiyinchiliklar o'sish jarayonining bir qismidir, qochmang, yuzlaning.",
        "🚀 Siz qila olasiz! Qayd etilgan narsa o'sadi: odatlaringizni kuzatib boring.",
        "🚀 Siz qila olasiz! Siz bu ishlarni \"qilishga majbur emassiz\", balki \"qilish imkoniyatiga egasiz\".",
    ],
    "en": [
        "🚀 You can do it! Motivation helps you start, but habit keeps you going.",
        "🚀 You can do it! We become what we repeatedly do. Excellence is not an accident, it is a habit.",
        "🚀 You can do it! First we shape our habits, then our habits shape us.",
        "🚀 You can do it! A 1% daily improvement makes you 37 times stronger in a year.",
        "🚀 You can do it! Success is not a one-time miracle, it is the product of daily small habits.",
        "🚀 You can do it! Discipline is stronger than motivation. Act based on your goal, not your mood.",
        "🚀 You can do it! You do not rise to the level of your goals, you fall to the level of your habits.",
        "🚀 You can do it! The hardest part is taking the first step. Just start.",
        "🚀 You can do it! Think big, but start with a tiny step.",
        "🚀 You can do it! Never miss twice in a row. The first miss is an accident, the second is the start of a bad habit.",
        "🚀 You can do it! Consistency is the key to any success.",
        "🚀 You can do it! Do not strive for perfection, strive for constant growth.",
        "🚀 You can do it! You cannot just quit a bad habit, you need to replace it with a better one.",
        "🚀 You can do it! Focus not on the result, but on becoming the person worthy of that result.",
        "🚀 You can do it! A habit is not a finish line to cross, it is a way of life.",
        "🚀 You can do it! Even on days when you feel low, do at least a little to keep the rule.",
        "🚀 You can do it! Do not rely on willpower, adapt your environment to your habits.",
        "🚀 You can do it! Make the right thing easy to do, and distractions hard to reach.",
        "🚀 You can do it! Do not wait for motivation, start acting and it will come.",
        "🚀 You can do it! What you do today can improve your entire future.",
        "🚀 You can do it! Time turns good habits into your friend and bad ones into your enemy.",
        "🚀 You can do it! Every small daily investment in yourself brings the greatest return in the future.",
        "🚀 You can do it! Great things are not done in a day, be patient.",
        "🚀 You can do it! Do not break the chain: consistency guarantees results.",
        "🚀 You can do it! Even if you do not see results yet, keep going. Roots always grow underground.",
        "🚀 You can do it! Your life today is simply the sum of your past habits.",
        "🚀 You can do it! Your first morning victory (habit) sets the tone for your entire day.",
        "🚀 You can do it! Challenges are part of the growth process. Do not run, face them.",
        "🚀 You can do it! What gets tracked gets improved: keep monitoring your habits.",
        "🚀 You can do it! You do not have to do this, you get to do this.",
    ],
    "ru": [
        "🚀 Ты справишься! Мотивация помогает начать, а привычка помогает продолжать.",
        "🚀 Ты справишься! Мы становимся тем, что делаем регулярно. Успех — не случайность, а привычка.",
        "🚀 Ты справишься! Сначала мы формируем привычки, а потом привычки формируют нас.",
        "🚀 Ты справишься! Ежедневный рост на 1% за год сделает тебя в 37 раз сильнее.",
        "🚀 Ты справишься! Успех — не разовое чудо, а результат ежедневных маленьких привычек.",
        "🚀 Ты справишься! Дисциплина сильнее мотивации. Действуй ради цели, а не по настроению.",
        "🚀 Ты справишься! Ты не поднимаешься до уровня целей, а опускаешься до уровня привычек.",
        "🚀 Ты справишься! Самое сложное — сделать первый шаг. Просто начни.",
        "🚀 Ты справишься! Думай масштабно, но начинай с крошечного шага.",
        "🚀 Ты справишься! Не пропускай дважды подряд. Первый пропуск — случайность, второй — начало плохой привычки.",
        "🚀 Ты справишься! Постоянство — ключ к любому успеху.",
        "🚀 Ты справишься! Не стремись к совершенству, стремись к постоянному росту.",
        "🚀 Ты справишься! Плохую привычку нельзя просто бросить, её нужно заменить хорошей.",
        "🚀 Ты справишься! Фокусируйся не на результате, а на том, чтобы стать достойным этого результата.",
        "🚀 Ты справишься! Привычка — это не финиш, а образ жизни.",
        "🚀 Ты справишься! Даже в плохие дни делай хотя бы немного, чтобы сохранить правило.",
        "🚀 Ты справишься! Не полагайся на силу воли, адаптируй среду под свои привычки.",
        "🚀 Ты справишься! Сделай правильное действие лёгким, а отвлекающее — трудным.",
        "🚀 Ты справишься! Не жди мотивацию, начни действовать — она придёт сама.",
        "🚀 Ты справишься! То, что ты делаешь сегодня, может улучшить всё твоё будущее.",
        "🚀 Ты справишься! Время превращает хорошие привычки в друга, а плохие — во врага.",
        "🚀 Ты справишься! Каждая маленькая ежедневная инвестиция в себя даёт самую большую отдачу.",
        "🚀 Ты справишься! Великие дела не делаются за один день, будь терпелив.",
        "🚀 Ты справишься! Не разрывай цепочку: непрерывность гарантирует результат.",
        "🚀 Ты справишься! Даже если не видишь результат, не останавливайся. Корни всегда растут под землёй.",
        "🚀 Ты справишься! Твоя сегодняшняя жизнь — это просто сумма прошлых привычек.",
        "🚀 Ты справишься! Первая утренняя победа (привычка) задаёт тон всему дню.",
        "🚀 Ты справишься! Трудности — часть роста. Не убегай, встречай их лицом.",
        "🚀 Ты справишься! То, что отслеживается — улучшается. Следи за своими привычками.",
        "🚀 Ты справишься! Ты не обязан это делать — у тебя есть возможность это делать.",
    ],
    "tr": ["💪 Her gün yeni bir fırsat!", "🔥 Seriyi bozma!", "🌟 Küçük adımlar büyük başarıya!", "🚀 Yapabilirsin!", "🎯 Hedefe bir adım daha!"],
    "kk": ["💪 Әр күн — жаңа мүмкіндік!", "🔥 Қатарыңызды үзбеңіз!", "🌟 Кіші қадамдар үлкен жетістікке!", "🚀 Сіз жасай аласыз!", "🎯 Мақсатқа бір қадам!"],
    "tg": ["💪 Ҳар рӯз имкони нав аст!", "🔥 Пайдаро нашикон!", "🌟 Қадамҳои хурд ба муваффақияти бузург!", "🚀 Шумо метавонед!", "🎯 Як қадам ба ҳадаф!"],
    "tk": ["💪 Her gün täze mümkinçilik!", "🔥 Yzygiderliligiňizi bozmaň!", "🌟 Kiçi ädimler uly üstünlige!", "🚀 Siz edip bilersiňiz!", "🎯 Maksada bir ädim!"],
    "ky": ["💪 Ар бир күн жаңы мүмкүнчүлүк!", "🔥 Катарыңызды үзбөңүз!", "🌟 Кичи кадамдар чоң ийгиликке!", "🚀 Сиз жасай аласыз!", "🎯 Максатка бир кадам!"],
    "de": ["💪 Jeder Tag ist eine neue Chance!", "🔥 Brich die Serie nicht!", "🌟 Kleine Schritte führen zu großem Erfolg!", "🚀 Du schaffst das!", "🎯 Einen Schritt näher am Ziel!"],
    "fr": ["💪 Chaque jour est une nouvelle chance!", "🔥 Ne brisez pas la série!", "🌟 Les petits pas mènent au grand succès!", "🚀 Vous pouvez le faire!", "🎯 Un pas de plus vers votre objectif!"],
}

