#!/usr/bin/env python3
"""
Ko'p til - LANGS dictionary
"""

LANGS = {
    "uz": {
        "choose_lang":       "🌐 Tilni tanlang:",
        "lang_set":          "✅ Til o'zgartirildi!",
        "welcome_new":       "👋 Salom, *{name}*!\n\n🌱 *Odatlar Shakllantirish Boti*ga xush kelibsiz!\n\nBu bot sizga:\n• Odatlarni belgilash\n• Vaqtida eslatma olish\n• Streak va statistika kuzatish\nimkonini beradi.\n\nBoshlash uchun *➕ Odat qo'shish* tugmasini bosing!",
        "welcome_back":      "📊 *ODATLARINGIZ:*",
        "btn_add":           "➕ Odat qo'shish",
        "btn_delete":        "🗑 Odatni o'chirish",
        "btn_stats":         "📊 Statistika",
        "btn_rating":        "🏆 Reyting",
        "btn_home":          "🏠 Asosiy menyu",
        "btn_enter":         "📃 Kirish",
        "weekly_share_caption": "Mening haftalik natijam | @Super_habits_bot",
        "share_fwd_btn": "📤 Ulashish",
        "share_del_btn": "✅ Tasdiqlash",
        "main_greeting":     "👋 *Assalomu alaykum, {name}!*\n\n🌱 Odatlaringizni barpo etish, rivojlantirish, kuzatib borish, qiziqarli raqobat, oson va tez shakllantirish uchun, eng to'g'ri joydasiz!\n\nUshbu sayohatni boshlash uchun:\n« 📃 *Kirish*» tugmasini bosing! 👇",
        "btn_cancel":        "❌ Bekor qilish",
        "btn_yes":           "Ha ✅",
        "btn_no":            "Yo'q ❌",
        "ask_habit_name":    "📝 Odatning nomini yozing:\n\n_Masalan: Kitob o'qish, Sport, Suv ichish..._",
        "ask_habit_time":    "*✅ Odat:* {name}\n\n*⏰ Eslatma vaqtini yozing* (24 soat):\n\n_Masalan: 07:30 yoki 21:00_",
        "habit_added":       "🎉 *{name}* odati qo'shildi!\n\n*⏰ Eslatma:* {time} da keladi\n*🔥 Streak:* 0 kun\n\nHar kuni vaqtida bajaring!",
        "wrong_time":        "❌ Noto'g'ri format. HH:MM formatida yozing.\n_Masalan: 08:00_",
        "no_habits":         "📭 Hali odat qo'shilmagan.\n\n➕ Odat qo'shish tugmasini bosing!",
        "no_stats":          "📭 Hali odat yo'q.",
        "confirm_delete":    "⚠️ Haqiqatan ham *{name}* odatini o'chirishni xohlaysizmi?",
        "deleted":           "🗑 *{name}* o'chirildi.",
        "no_delete":         "📭 O'chirish uchun odat yo'q.",
        "done_today":        "✅ Bugun allaqachon bajardingiz!",
        "done_ok":           "*✅ {name}* — bajarildi!",
        "undone":            "*❌ {name}* — bekor qilindi!",
        "all_done":          "Bugungi barcha odatni bajardingiz, tabriklaymiz 🎉",
        "limit":             "⚠️ Odatlarni yaratish me'yori 15 ta!",
        "remind_title":      "⏰ *Eslatma!*\n\n*🎯 Odat:* {name}\n\n{motiv}",
        "btn_done":          "✅ Bajardim!",
        "btn_skip":          "❌ Bajarmadim",
        "stats_title":       "*📊 Statistika —* {page}/{total} sahifa",
        "stats_ball":        "*⭐ Jami ball:* {ball} ball",
        "stats_rank":        "*🎖 Daraja:* {rank}",
        "stats_streak":      "*🔥 Streak:* {streak} kun",
        "stats_time":        "*⏰ Vaqt:* {time}",
        "stats_ball2":       "⭐ Odat balli: {ball} ball",
        "stats_done":        "*✅ Jami bajarilgan:* {n} marta",
        "stats_missed":      "*❌ Jami bajarilmagan:* {n} marta",
        "stats_last":        "*📅 Oxirgi:* {d}",
        "rating_title":      "🏆 Top 10 Reyiting",
        "rating_empty":      "Hali hech kim ball to'plamagan.",
        "sub_required":      "⚠️ Botdan foydalanish uchun avvalo kanalga a'zo bo'ling!",
        "btn_join":          "📢 Kanalga o'tish",
        "btn_joined":        "✅ A'zo bo'ldim",
        "invalid_msg":       "⚠️ Sizning noaniq habarlaringiz qo'llab quvvatlanmaydi.",
        "nav_prev":          "⬅️ {n}-sahifa",
        "nav_next":          "{n}-sahifa ➡️",
        "ranks":             ["🌱 Yangi boshlovchi","🥉 Boshlang'ich","🥈 Tajribali","🥇 Professional","💎 Master","🏆 Legenda"],
        "btn_settings":      "⚙️ Sozlamalar",
        "settings_title":    "⚙️ *Muhim sozlamalar qismi.*",
        "btn_change_lang":   "🌐 Tilni o'zgartirish",
        "btn_change_info":   "📝 Ma'lumotlarni o'zgartirish",
        "change_info_text":  "📝 *Ma'lumotlarni o'zgartirish*\n\nNimani o'zgartirmoqchisiz?",
        "rating_no_link":    "username yo'q",
        "hint_toggle":       "Tugmalarni bosish orqali ham odatni tasdiqlashingiz mumkin!",
        "done_percent":      "*Bajarildi:* {p}%",
        "share_phone":       "📱 Telefon raqamni yuborish",
        "ask_phone":         "📱 Telefon raqamingizni yuboring yoki qo'lda kiriting:\n\n_Masalan: +998901234567_",
        "err_wrong_phone":   "⚠️ Noto'g'ri raqam. Masalan: *+998901234567*",
        "err_wrong_count":   "⚠️ Noto'g'ri son. 1 dan 20 gacha raqam kiriting:",
        "err_time_format":   "⚠️ Noto'g'ri format. Masalan: *HH:MM*",
        "err_time_value":    "⚠️ Noto'g'ri vaqt. Masalan: *HH:MM*",
        "err_min_chars":     "⚠️ Kamida 2 harf kiriting!",
        "err_positive_num":  "⚠️ Musbat son kiriting!",
        "err_only_digits":   "⚠️ Faqat raqam kiriting!",
        "err_enter_number":  "⚠️ Son kiriting. Masalan: 100 yoki -50",
        "err_user_not_found":"⚠️ Bu ID foydalanuvchi topilmadi.",
        "err_self_transfer": "⚠️ O'zingizga ball yubora olmaysiz!",
        "err_not_enough_pts":"⚠️ Sizda faqat *{points} ball* bor!",
        "err_max_groups":    "⚠️ Siz admin sifatida 3 tadan ko'p guruh yarata olmaysiz.",
        "set_dev_prompt":    "💬 *Dasturchiga habar yozing:*\n\nHabaringizni quyida kiriting:",
        "set_habit_settings":"⚙️ *Odat sozlamalari*",
        "set_all_notime":    "🔕 Barcha odatlar vaqtsiz holatga o'tkazildi!",
        "set_which_time":    "⏰ *Qaysi odatning vaqtini tahrirlash?*",
        "set_habit_notime":  "🔕 Odat vaqtsiz holatga o'tkazildi!",
        "set_edit_times":    "⏰ *Odatlar vaqtini tahrirlash*",
        "set_which_rename":  "✏️ *Qaysi odatning nomini o'zgartirmoqchisiz?*",
        "set_new_name":      "✏️ Yangi ismingizni yozing:",
        "set_all_time_ask":  "⏰ Barcha odatlar uchun umumiy vaqtni kiriting:\n\n_Masalan: 07:00_",
        "ok_time_updated":   "✅ Vaqt yangilandi!",
        "ok_all_times":      "✅ Barcha odatlar vaqti *{time}* ga o'zgartirildi!",
        "ok_name_changed":   "✅ Ism *{name}* ga o'zgartirildi!",
        "ok_habit_renamed":  "✅ Odat nomi *{name}* ga o'zgartirildi!",
        "ok_dev_sent":       "✅ Xabaringiz dasturchiga yuborildi!",
        "ok_transfer":       "✅ *{amount} ball* muvaffaqiyatli yuborildi!\n\n⭐ Qolgan ballingiz: {points}",
        "ok_points_reset":   "✅ Ballaringiz *0 ga* tushirildi.",
        "del_which_habit":   "🗑 *Qaysi odatni o'chirmoqchisiz?*",
        "add_more_habits":   "➕ *Yana odat qo'shing:*",
        "ok_self_deduct":    "✅ *{amount} ball* ayirib tashlandi.\n\n⭐ Qolgan ballingiz: {points}",
        "admin_gave_pts":    "🎁 Admin sizga *{amount} ball* berdi!\n\n⭐ Hisobingiz: {points} ball",
        "admin_reply":       "↩️ *Admin javobi:*\n\n{text}",
    },
    "en": {
        "choose_lang":       "🌐 Choose language:",
        "lang_set":          "✅ Language changed!",
        "welcome_new":       "👋 Hello, *{name}*!\n\n🌱 Welcome to *Habit Tracker Bot*!\n\nThis bot helps you:\n• Set habits\n• Get timely reminders\n• Track streaks & stats\n\nPress *➕ Add Habit* to start!",
        "welcome_back":      "📊 *YOUR HABITS:*",
        "btn_add":           "➕ Add Habit",
        "btn_delete":        "🗑 Delete Habit",
        "btn_stats":         "📊 Statistics",
        "btn_rating":        "🏆 Leaderboard",
        "btn_home":          "🏠 Main Menu",
        "btn_enter":         "📃 Open",
        "weekly_share_caption": "My weekly results | @Super_habits_bot",
        "share_fwd_btn": "📤 Share",
        "share_del_btn": "✅ Confirm",
        "main_greeting":     "👋 *Hello, {name}!*\n\n🌱 You're in the right place to build, develop and track your habits, compete with friends, and grow every day!\n\nTo start your journey:\nTap the « 📃 *Open*» button! 👇",
        "btn_cancel":        "❌ Cancel",
        "btn_yes":           "Yes ✅",
        "btn_no":            "No ❌",
        "ask_habit_name":    "📝 Enter habit name:\n\n_Example: Reading, Exercise, Drink water..._",
        "ask_habit_time":    "*✅ Habit:* {name}\n\n*⏰ Enter reminder time* (24h):\n\n_Example: 07:30 or 21:00_",
        "habit_added":       "🎉 Habit *{name}* added!\n\n*⏰ Reminder:* {time}\n*🔥 Streak:* 0 days\n\nComplete it daily!",
        "wrong_time":        "❌ Wrong format. Use HH:MM.\n_Example: 08:00_",
        "no_habits":         "📭 No habits yet.\n\nPress ➕ Add Habit!",
        "no_stats":          "📭 No habits yet.",
        "confirm_delete":    "⚠️ Really delete *{name}*?",
        "deleted":           "🗑 *{name}* deleted.",
        "no_delete":         "📭 No habits to delete.",
        "done_today":        "✅ Already done today!",
        "done_ok":           "*✅ {name}* — done!",
        "undone":            "*❌ {name}* — undone!",
        "all_done":          "You completed all today's habits, congratulations 🎉",
        "limit":             "⚠️ Maximum 15 habits allowed!",
        "remind_title":      "⏰ *Reminder!*\n\n*🎯 Habit:* {name}\n\n{motiv}",
        "btn_done":          "✅ Done!",
        "btn_skip":          "❌ Not done",
        "stats_title":       "*📊 Statistics —* page {page}/{total}",
        "stats_ball":        "⭐ *Total points: {ball}*",
        "stats_rank":        "🎖 Rank: {rank}",
        "stats_streak":      "🔥 Streak: {streak} days",
        "stats_time":        "⏰ Time: {time}",
        "stats_ball2":       "⭐ Habit points: {ball}",
        "stats_done":        "✅ Total done: {n} times",
        "stats_missed":      "❌ Total missed: {n} times",
        "stats_last":        "📅 Last: {d}",
        "rating_title":      "🏆 Top 10 Leaderboard",
        "rating_empty":      "Nobody has points yet.",
        "sub_required":      "⚠️ Please join the channel to use the bot!",
        "btn_join":          "📢 Join Channel",
        "btn_joined":        "✅ I joined",
        "invalid_msg":       "⚠️ Unknown message, not supported.",
        "nav_prev":          "⬅️ Page {n}",
        "nav_next":          "Page {n} ➡️",
        "ranks":             ["🌱 Beginner","🥉 Novice","🥈 Experienced","🥇 Professional","💎 Master","🏆 Legend"],
        "btn_settings":      "⚙️ Settings",
        "settings_title":    "⚙️ *Settings*",
        "btn_change_lang":   "🌐 Change Language",
        "btn_change_info":   "📝 Change Profile",
        "change_info_text":  "📝 *Change Profile*\n\nWhat would you like to change?",
        "rating_no_link":    "no username",
        "hint_toggle":       "You can also confirm habits by pressing the buttons!",
        "done_percent":      "*Done:* {p}%",
        "share_phone":       "📱 Share phone number",
        "ask_phone":         "📱 Share your phone number or type it manually:\n\n_Example: +998901234567_",
        "err_wrong_phone":   "⚠️ Wrong number. Example: *+998901234567*",
        "err_wrong_count":   "⚠️ Wrong number. Enter 1 to 20:",
        "err_time_format":   "⚠️ Wrong format. Example: *HH:MM*",
        "err_time_value":    "⚠️ Wrong time. Example: *HH:MM*",
        "err_min_chars":     "⚠️ Enter at least 2 characters!",
        "err_positive_num":  "⚠️ Enter a positive number!",
        "err_only_digits":   "⚠️ Enter digits only!",
        "err_enter_number":  "⚠️ Enter a number. Example: 100 or -50",
        "err_user_not_found":"⚠️ User with this ID not found.",
        "err_self_transfer": "⚠️ You cannot send points to yourself!",
        "err_not_enough_pts":"⚠️ You only have *{points} points*!",
        "err_max_groups":    "⚠️ You can create a maximum of 3 groups as admin.",
        "set_dev_prompt":    "💬 *Write to the developer:*\n\nType your message below:",
        "set_habit_settings":"⚙️ *Habit settings*",
        "set_all_notime":    "🔕 All habits set to no-time mode!",
        "set_which_time":    "⏰ *Which habit time to edit?*",
        "set_habit_notime":  "🔕 Habit set to no-time mode!",
        "set_edit_times":    "⏰ *Edit habit times*",
        "set_which_rename":  "✏️ *Which habit to rename?*",
        "set_new_name":      "✏️ Enter your new name:",
        "set_all_time_ask":  "⏰ Enter a common time for all habits:\n\n_Example: 07:00_",
        "ok_time_updated":   "✅ Time updated!",
        "ok_all_times":      "✅ All habits time changed to *{time}*!",
        "ok_name_changed":   "✅ Name changed to *{name}*!",
        "ok_habit_renamed":  "✅ Habit renamed to *{name}*!",
        "ok_dev_sent":       "✅ Your message was sent to the developer!",
        "ok_transfer":       "✅ *{amount} points* sent successfully!\n\n⭐ Remaining: {points}",
        "ok_points_reset":   "✅ Your points have been reset to *0*.",
        "del_which_habit":   "🗑 *Which habit to delete?*",
        "add_more_habits":   "➕ *Add another habit:*",
        "ok_self_deduct":    "✅ *{amount} points* deducted.\n\n⭐ Remaining: {points}",
        "admin_gave_pts":    "🎁 Admin gave you *{amount} points*!\n\n⭐ Balance: {points} points",
        "admin_reply":       "↩️ *Admin reply:*\n\n{text}",
    },
    "ru": {
        "choose_lang":       "🌐 Выберите язык:",
        "lang_set":          "✅ Язык изменён!",
        "welcome_new":       "👋 Привет, *{name}*!\n\n🌱 Добро пожаловать в *Бот трекер привычек*!\n\nЭтот бот поможет вам:\n• Отслеживать привычки\n• Получать напоминания\n• Вести статистику\n\nНажмите *➕ Добавить привычку*!",
        "welcome_back":      "📊 *ВАШИ ПРИВЫЧКИ:*",
        "btn_add":           "➕ Добавить",
        "btn_delete":        "🗑 Удалить",
        "btn_stats":         "📊 Статистика",
        "btn_rating":        "🏆 Рейтинг",
        "btn_home":          "🏠 Главное меню",
        "btn_enter":         "📃 Войти",
        "weekly_share_caption": "Мои результаты за неделю | @Super_habits_bot",
        "share_fwd_btn": "📤 Поделиться",
        "share_del_btn": "✅ Подтвердить",
        "main_greeting":     "👋 *Здравствуйте, {name}!*\n\n🌱 Вы в правильном месте для создания, развития и отслеживания привычек, соревнований с друзьями и ежедневного роста!\n\nЧтобы начать путешествие:\nНажмите кнопку « 📃 *Войти*»! 👇",
        "btn_cancel":        "❌ Отмена",
        "btn_yes":           "Да ✅",
        "btn_no":            "Нет ❌",
        "ask_habit_name":    "📝 Введите название привычки:\n\n_Пример: Чтение, Спорт, Вода..._",
        "ask_habit_time":    "*✅ Привычка:* {name}\n\n*⏰ Введите время* (24ч):\n\n_Пример: 07:30 или 21:00_",
        "habit_added":       "🎉 Привычка *{name}* добавлена!\n\n*⏰ Напоминание:* {time}\n*🔥 Серия:* 0 дней\n\nВыполняйте каждый день!",
        "wrong_time":        "❌ Неверный формат. Используйте ЧЧ:ММ.\n_Пример: 08:00_",
        "no_habits":         "📭 Привычек пока нет.\n\nНажмите ➕ Добавить!",
        "no_stats":          "📭 Привычек пока нет.",
        "confirm_delete":    "⚠️ Удалить привычку *{name}*?",
        "deleted":           "🗑 *{name}* удалена.",
        "no_delete":         "📭 Нет привычек для удаления.",
        "done_today":        "✅ Уже выполнено сегодня!",
        "done_ok":           "*✅ {name}* — выполнено!",
        "undone":            "*❌ {name}* — отменено!",
        "all_done":          "Вы выполнили все привычки сегодня, поздравляем 🎉",
        "limit":             "⚠️ Максимум 15 привычек!",
        "remind_title":      "⏰ *Напоминание!*\n\n*🎯 Привычка:* {name}\n\n{motiv}",
        "btn_done":          "✅ Выполнено!",
        "btn_skip":          "❌ Не выполнено",
        "stats_title":       "📊 *Статистика* — стр. {page}/{total}",
        "stats_ball":        "⭐ *Всего очков: {ball}*",
        "stats_rank":        "🎖 Уровень: {rank}",
        "stats_streak":      "🔥 Серия: {streak} дней",
        "stats_time":        "⏰ Время: {time}",
        "stats_ball2":       "⭐ Очки за привычку: {ball}",
        "stats_done":        "✅ Всего выполнено: {n} раз",
        "stats_missed":      "❌ Всего пропущено: {n} раз",
        "stats_last":        "📅 Последнее: {d}",
        "rating_title":      "🏆 Топ 10",
        "rating_empty":      "Никто ещё не набрал очков.",
        "sub_required":      "⚠️ Подпишитесь на канал, чтобы использовать бота!",
        "btn_join":          "📢 Перейти на канал",
        "btn_joined":        "✅ Я подписался",
        "invalid_msg":       "⚠️ Неизвестное сообщение, не поддерживается.",
        "nav_prev":          "⬅️ Стр. {n}",
        "nav_next":          "Стр. {n} ➡️",
        "ranks":             ["🌱 Новичок","🥉 Начинающий","🥈 Опытный","🥇 Профессионал","💎 Мастер","🏆 Легенда"],
        "btn_settings":      "⚙️ Настройки",
        "settings_title":    "⚙️ *Настройки*",
        "btn_change_lang":   "🌐 Изменить язык",
        "btn_change_info":   "📝 Изменить профиль",
        "change_info_text":  "📝 *Изменить профиль*\n\nЧто хотите изменить?",
        "rating_no_link":    "нет username",
        "hint_toggle":       "Вы также можете подтверждать привычки нажатием кнопок!",
        "done_percent":      "*Выполнено:* {p}%",
        "share_phone":       "📱 Отправить номер телефона",
        "ask_phone":         "📱 Отправьте номер телефона или введите вручную:\n\n_Пример: +998901234567_",
        "err_wrong_phone":   "⚠️ Неверный номер. Пример: *+998901234567*",
        "err_wrong_count":   "⚠️ Неверное число. Введите от 1 до 20:",
        "err_time_format":   "⚠️ Неверный формат. Пример: *ЧЧ:ММ*",
        "err_time_value":    "⚠️ Неверное время. Пример: *ЧЧ:ММ*",
        "err_min_chars":     "⚠️ Введите минимум 2 символа!",
        "err_positive_num":  "⚠️ Введите положительное число!",
        "err_only_digits":   "⚠️ Введите только цифры!",
        "err_enter_number":  "⚠️ Введите число. Пример: 100 или -50",
        "err_user_not_found":"⚠️ Пользователь с таким ID не найден.",
        "err_self_transfer": "⚠️ Нельзя отправить баллы самому себе!",
        "err_not_enough_pts":"⚠️ У вас только *{points} баллов*!",
        "err_max_groups":    "⚠️ Как админ вы можете создать максимум 3 группы.",
        "set_dev_prompt":    "💬 *Напишите разработчику:*\n\nВведите сообщение ниже:",
        "set_habit_settings":"⚙️ *Настройки привычек*",
        "set_all_notime":    "🔕 Все привычки переведены в режим без времени!",
        "set_which_time":    "⏰ *Время какой привычки изменить?*",
        "set_habit_notime":  "🔕 Привычка переведена в режим без времени!",
        "set_edit_times":    "⏰ *Редактировать время привычек*",
        "set_which_rename":  "✏️ *Какую привычку переименовать?*",
        "set_new_name":      "✏️ Введите новое имя:",
        "set_all_time_ask":  "⏰ Введите общее время для всех привычек:\n\n_Пример: 07:00_",
        "ok_time_updated":   "✅ Время обновлено!",
        "ok_all_times":      "✅ Время всех привычек изменено на *{time}*!",
        "ok_name_changed":   "✅ Имя изменено на *{name}*!",
        "ok_habit_renamed":  "✅ Привычка переименована в *{name}*!",
        "ok_dev_sent":       "✅ Сообщение отправлено разработчику!",
        "ok_transfer":       "✅ *{amount} баллов* успешно отправлено!\n\n⭐ Остаток: {points}",
        "ok_points_reset":   "✅ Ваши баллы сброшены до *0*.",
        "del_which_habit":   "🗑 *Какую привычку удалить?*",
        "add_more_habits":   "➕ *Добавьте ещё привычку:*",
        "ok_self_deduct":    "✅ *{amount} баллов* списано.\n\n⭐ Остаток: {points}",
        "admin_gave_pts":    "🎁 Админ начислил вам *{amount} баллов*!\n\n⭐ Баланс: {points} баллов",
        "admin_reply":       "↩️ *Ответ админа:*\n\n{text}",
    },
    "tr": {
        "choose_lang":       "🌐 Dil seçin:",
        "lang_set":          "✅ Dil değiştirildi!",
        "welcome_new":       "👋 Merhaba, *{name}*!\n\n🌱 *Alışkanlık Takip Botu*'na hoş geldiniz!\n\nBu bot size:\n• Alışkanlık belirleme\n• Zamanında hatırlatma\n• İstatistik takibi\nimkanı verir.\n\n*➕ Alışkanlık Ekle*'ye basın!",
        "welcome_back":      "📊 *ALISKANLIKLARINIZ:*",
        "btn_add":           "➕ Alışkanlık Ekle",
        "btn_delete":        "🗑 Sil",
        "btn_stats":         "📊 İstatistik",
        "btn_rating":        "🏆 Sıralama",
        "btn_home":          "🏠 Ana Menü",
        "btn_cancel":        "❌ İptal",
        "btn_yes":           "Evet ✅",
        "btn_no":            "Hayır ❌",
        "ask_habit_name":    "📝 Alışkanlık adını yazın:\n\n_Örnek: Kitap okuma, Spor, Su içme..._",
        "ask_habit_time":    "*✅ Alışkanlık:* {name}\n\n*⏰ Hatırlatma saatini girin* (24 saat):\n\n_Örnek: 07:30 veya 21:00_",
        "habit_added":       "🎉 *{name}* alışkanlığı eklendi!\n\n⏰ Hatırlatma: *{time}*\n🔥 Seri: 0 gün\n\nHer gün yapın!",
        "wrong_time":        "❌ Yanlış format. SS:DD formatında girin.\n_Örnek: 08:00_",
        "no_habits":         "📭 Henüz alışkanlık yok.\n\n➕ Ekle butonuna basın!",
        "no_stats":          "📭 Henüz alışkanlık yok.",
        "confirm_delete":    "⚠️ *{name}* alışkanlığını silmek istiyor musunuz?",
        "deleted":           "🗑 *{name}* silindi.",
        "no_delete":         "📭 Silinecek alışkanlık yok.",
        "done_today":        "✅ Bugün zaten yapıldı!",
        "done_ok":           "*✅ {name}* — yapıldı!",
        "undone":            "*❌ {name}* — geri alındı!",
        "all_done":          "Bugünkü tüm alışkanlıkları tamamladınız, tebrikler 🎉",
        "limit":             "⚠️ Maksimum 15 alışkanlık!",
        "remind_title":      "⏰ *Hatırlatma!*\n\n*🎯 Alışkanlık:* {name}\n\n{motiv}",
        "btn_done":          "✅ Yaptım!",
        "btn_skip":          "❌ Yapmadım",
        "stats_title":       "📊 *İstatistik* — {page}/{total}. sayfa",
        "stats_ball":        "⭐ *Toplam puan: {ball}*",
        "stats_rank":        "🎖 Seviye: {rank}",
        "stats_streak":      "🔥 Seri: {streak} gün",
        "stats_time":        "⏰ Saat: {time}",
        "stats_ball2":       "⭐ Alışkanlık puanı: {ball}",
        "stats_done":        "✅ Toplam yapılan: {n} kez",
        "stats_missed":      "❌ Toplam kaçırılan: {n} kez",
        "stats_last":        "📅 Son: {d}",
        "rating_title":      "🏆 İlk 10",
        "rating_empty":      "Henüz kimse puan kazanmadı.",
        "sub_required":      "⚠️ Botu kullanmak için kanala katılın!",
        "btn_join":          "📢 Kanala Git",
        "btn_joined":        "✅ Katıldım",
        "invalid_msg":       "⚠️ Bilinmeyen mesaj, desteklenmiyor.",
        "nav_prev":          "⬅️ {n}. sayfa",
        "nav_next":          "{n}. sayfa ➡️",
        "ranks":             ["🌱 Başlangıç","🥉 Acemi","🥈 Deneyimli","🥇 Profesyonel","💎 Usta","🏆 Efsane"],
        "btn_settings":      "⚙️ Ayarlar",
        "settings_title":    "⚙️ *Ayarlar*",
        "btn_change_lang":   "🌐 Dil Değiştir",
        "btn_change_info":   "📝 Profili Düzenle",
        "change_info_text":  "📝 *Profili Düzenle*\n\nNeyi değiştirmek istersiniz?",
        "rating_no_link":    "username yok",
        "hint_toggle":       "Butonlara basarak da alışkanlıkları onaylayabilirsiniz!",
        "done_percent":      "*Tamamlandı:* {p}%",
        "share_phone":       "📱 Telefon numarasını paylaş",
        "ask_phone":         "📱 Telefon numaranızı gönderin veya elle girin:\n\n_Örnek: +998901234567_",
    },
    "kk": {
        "choose_lang":       "🌐 Тілді таңдаңыз:",
        "lang_set":          "✅ Тіл өзгертілді!",
        "welcome_new":       "👋 Сәлем, *{name}*!\n\n🌱 *Дағды бақылау ботына* қош келдіңіз!\n\nБот сізге:\n• Дағдыларды белгілеу\n• Уақтылы еске салу\n• Статистика жүргізу\nмүмкіндігін береді.\n\n*➕ Дағды қосу* түймесін басыңыз!",
        "welcome_back":      "📊 *ДАҒДЫЛАРЫҢЫЗ:*",
        "btn_add":           "➕ Дағды қосу",
        "btn_delete":        "🗑 Жою",
        "btn_stats":         "📊 Статистика",
        "btn_rating":        "🏆 Рейтинг",
        "btn_home":          "🏠 Басты мәзір",
        "btn_cancel":        "❌ Болдырмау",
        "btn_yes":           "Иә ✅",
        "btn_no":            "Жоқ ❌",
        "ask_habit_name":    "📝 Дағды атауын жазыңыз:\n\n_Мысалы: Кітап оқу, Спорт, Су ішу..._",
        "ask_habit_time":    "*✅ Дағды:* {name}\n\n*⏰ Еске салу уақытын енгізіңіз* (24 сағ):\n\n_Мысалы: 07:30 немесе 21:00_",
        "habit_added":       "🎉 *{name}* дағдысы қосылды!\n\n⏰ Еске салу: *{time}*\n🔥 Streak: 0 күн\n\nКүн сайын орындаңыз!",
        "wrong_time":        "❌ Қате формат. СС:ММ форматында жазыңыз.\n_Мысалы: 08:00_",
        "no_habits":         "📭 Әлі дағды жоқ.\n\n➕ Дағды қосыңыз!",
        "no_stats":          "📭 Әлі дағды жоқ.",
        "confirm_delete":    "⚠️ *{name}* дағдысын жоюды растайсыз ба?",
        "deleted":           "🗑 *{name}* жойылды.",
        "no_delete":         "📭 Жоятын дағды жоқ.",
        "done_today":        "✅ Бүгін орындалды!",
        "done_ok":           "*✅ {name}* — орындалды!",
        "undone":            "*❌ {name}* — болдырылмады!",
        "all_done":          "Бүгінгі барлық дағдыны орындадыңыз, құттықтаймыз 🎉",
        "limit":             "⚠️ Максимум 15 дағды!",
        "remind_title":      "⏰ *Еске салу!*\n\n🎯 Дағды: *{name}*\n\n{motiv}",
        "btn_done":          "✅ Орындадым!",
        "btn_skip":          "❌ Орындамадым",
        "stats_title":       "📊 *Статистика* — {page}/{total} бет",
        "stats_ball":        "⭐ *Жалпы ұпай: {ball}*",
        "stats_rank":        "🎖 Деңгей: {rank}",
        "stats_streak":      "🔥 Streak: {streak} күн",
        "stats_time":        "⏰ Уақыт: {time}",
        "stats_ball2":       "⭐ Дағды ұпайы: {ball}",
        "stats_done":        "✅ Барлығы орындалды: {n} рет",
        "stats_missed":      "❌ Барлығы өткізілді: {n} рет",
        "stats_last":        "📅 Соңғы: {d}",
        "rating_title":      "🏆 Топ 10",
        "rating_empty":      "Ешкім ұпай жинаған жоқ.",
        "sub_required":      "⚠️ Ботты пайдалану үшін арнаға жазылыңыз!",
        "btn_join":          "📢 Арнаға өту",
        "btn_joined":        "✅ Жазылдым",
        "invalid_msg":       "⚠️ Белгісіз хабар, қолданылмайды.",
        "nav_prev":          "⬅️ {n}-бет",
        "nav_next":          "{n}-бет ➡️",
        "ranks":             ["🌱 Жаңадан бастаушы","🥉 Бастаушы","🥈 Тәжірибелі","🥇 Кәсіби","💎 Шебер","🏆 Легенда"],
        "btn_settings":      "⚙️ Параметрлер",
        "settings_title":    "⚙️ *Параметрлер*",
        "btn_change_lang":   "🌐 Тілді өзгерту",
        "btn_change_info":   "📝 Деректерді өзгерту",
        "change_info_text":  "📝 *Деректерді өзгерту*\n\nНені өзгерткіңіз келеді?",
        "rating_no_link":    "username жоқ",
        "hint_toggle":       "Дағдыны түймелер арқылы да растауға болады!",
        "done_percent":      "*Орындалды:* {p}%",
        "share_phone":       "📱 Телефон нөмірін жіберу",
        "ask_phone":         "📱 Телефон нөміріңізді жіберіңіз:\n\n_Мысалы: +998901234567_",
    },
    "tg": {
        "choose_lang":       "🌐 Забонро интихоб кунед:",
        "lang_set":          "✅ Забон тағйир ёфт!",
        "welcome_new":       "👋 Салом, *{name}*!\n\n🌱 Ба *Боти пайгирии одат* хуш омадед!\n\nИн бот ба шумо:\n• Муайян кардани одатҳо\n• Огоҳии саривақтӣ\n• Назорати оморӣ\nимкон медиҳад.\n\n*➕ Илова кардани одат* -ро пахш кунед!",
        "welcome_back":      "📊 *ОДАТҲОИ ШУМО:*",
        "btn_add":           "➕ Илова кардан",
        "btn_delete":        "🗑 Нест кардан",
        "btn_stats":         "📊 Омор",
        "btn_rating":        "🏆 Рейтинг",
        "btn_home":          "🏠 Менюи асосӣ",
        "btn_cancel":        "❌ Бекор кардан",
        "btn_yes":           "Бале ✅",
        "btn_no":            "Не ❌",
        "ask_habit_name":    "📝 Номи одатро нависед:\n\n_Масалан: Китобхонӣ, Варзиш, Нӯшидани об..._",
        "ask_habit_time":    "*✅ Одат:* {name}\n\n*⏰ Вақти огоҳиро ворид кунед* (24 соат):\n\n_Масалан: 07:30 ё 21:00_",
        "habit_added":       "🎉 Одати *{name}* илова шуд!\n\n⏰ Огоҳӣ: *{time}*\n🔥 Streak: 0 рӯз\n\nҲар рӯз иҷро кунед!",
        "wrong_time":        "❌ Формати нодуруст. СС:ДД навишта шавад.\n_Масалан: 08:00_",
        "no_habits":         "📭 Ҳоло одате нест.\n\n➕ Одат илова кунед!",
        "no_stats":          "📭 Ҳоло одате нест.",
        "confirm_delete":    "⚠️ Воқеан одати *{name}* -ро нест кардан мехоҳед?",
        "deleted":           "🗑 *{name}* нест шуд.",
        "no_delete":         "📭 Одате барои нест кардан нест.",
        "done_today":        "✅ Имрӯз аллакай иҷро шуд!",
        "done_ok":           "*✅ {name}* — иҷро шуд!",
        "undone":            "*❌ {name}* — бекор шуд!",
        "all_done":          "Шумо ҳамаи одатҳои имрӯзро иҷро кардед, табрик 🎉",
        "limit":             "⚠️ Ҳадди аксар 15 одат!",
        "remind_title":      "⏰ *Огоҳӣ!*\n\n🎯 Одат: *{name}*\n\n{motiv}",
        "btn_done":          "✅ Иҷро кардам!",
        "btn_skip":          "❌ Иҷро накардам",
        "stats_title":       "📊 *Омор* — {page}/{total} саҳифа",
        "stats_ball":        "⭐ *Ҷамъи хол: {ball}*",
        "stats_rank":        "🎖 Дараҷа: {rank}",
        "stats_streak":      "🔥 Streak: {streak} рӯз",
        "stats_time":        "⏰ Вақт: {time}",
        "stats_ball2":       "⭐ Холи одат: {ball}",
        "stats_done":        "✅ Ҷамъан иҷро шуд: {n} маротиба",
        "stats_missed":      "❌ Ҷамъан иҷро нашуд: {n} маротиба",
        "stats_last":        "📅 Охирин: {d}",
        "rating_title":      "🏆 Топ 10",
        "rating_empty":      "Ҳоло ҳеҷ кас хол ҷамъ накардааст.",
        "sub_required":      "⚠️ Барои истифодаи бот ба канал обуна шавед!",
        "btn_join":          "📢 Рафтан ба канал",
        "btn_joined":        "✅ Обуна шудам",
        "invalid_msg":       "⚠️ Паёми номаълум дастгирӣ намешавад.",
        "nav_prev":          "⬅️ Саҳифаи {n}",
        "nav_next":          "Саҳифаи {n} ➡️",
        "ranks":             ["🌱 Тозакор","🥉 Иштидоӣ","🥈 Ботаҷриба","🥇 Касбӣ","💎 Устод","🏆 Афсона"],
        "btn_settings":      "⚙️ Танзимот",
        "settings_title":    "⚙️ *Танзимот*",
        "btn_change_lang":   "🌐 Иваз кардани забон",
        "btn_change_info":   "📝 Иваз кардани маълумот",
        "change_info_text":  "📝 *Иваз кардани маълумот*\n\nЧиро иваз кардан мехоҳед?",
        "rating_no_link":    "username нест",
        "hint_toggle":       "Тавассути тугмаҳо низ одатро тасдиқ кардан мумкин!",
        "done_percent":      "*Иҷро шуд:* {p}%",
        "share_phone":       "📱 Рақами телефонро фиристед",
        "ask_phone":         "📱 Рақами телефонро фиристед:\n\n_Масалан: +998901234567_",
    },
    "tk": {
        "choose_lang":       "🌐 Dili saýlaň:",
        "lang_set":          "✅ Dil üýtgedildi!",
        "welcome_new":       "👋 Salam, *{name}*!\n\n🌱 *Endik yzarlaýjy bota* hoş geldiňiz!\n\nBu bot size:\n• Endikleri belgelemek\n• Wagtynda ýatlatma almak\n• Statistika ýöretmek\nmümkinçiligini berýär.\n\n*➕ Endik goşmak* düwmesine basyň!",
        "welcome_back":      "📊 *ENDIKLERIŇIZ:*",
        "btn_add":           "➕ Endik goşmak",
        "btn_delete":        "🗑 Pozmak",
        "btn_stats":         "📊 Statistika",
        "btn_rating":        "🏆 Reýting",
        "btn_home":          "🏠 Baş menýu",
        "btn_cancel":        "❌ Ýatyr",
        "btn_yes":           "Hawa ✅",
        "btn_no":            "Ýok ❌",
        "ask_habit_name":    "📝 Endigiň adyny ýazyň:\n\n_Mysal: Kitap okamak, Sport, Suw içmek..._",
        "ask_habit_time":    "*✅ Endik:* {name}\n\n*⏰ Ýatlatma wagtyny giriziň* (24 sagat):\n\n_Mysal: 07:30 ýa-da 21:00_",
        "habit_added":       "🎉 *{name}* endigi goşuldy!\n\n⏰ Ýatlatma: *{time}*\n🔥 Streak: 0 gün\n\nHer gün ýerine ýetiriň!",
        "wrong_time":        "❌ Nädogry format. SS:MM formatynda ýazyň.\n_Mysal: 08:00_",
        "no_habits":         "📭 Entek endik ýok.\n\n➕ Endik goşuň!",
        "no_stats":          "📭 Entek endik ýok.",
        "confirm_delete":    "⚠️ *{name}* endigi pozmak isleýärsiňizmi?",
        "deleted":           "🗑 *{name}* pozuldy.",
        "no_delete":         "📭 Pozmak üçin endik ýok.",
        "done_today":        "✅ Şu gün eýýäm edildi!",
        "done_ok":           "*✅ {name}* — edildi!",
        "undone":            "*❌ {name}* — ýatyryldy!",
        "all_done":          "Şu günki ähli endikleri tamamladyňyz, gutlaýarys 🎉",
        "limit":             "⚠️ Iň köp 15 endik!",
        "remind_title":      "⏰ *Ýatlatma!*\n\n🎯 Endik: *{name}*\n\n{motiv}",
        "btn_done":          "✅ Etdim!",
        "btn_skip":          "❌ Etmedim",
        "stats_title":       "📊 *Statistika* — {page}/{total} sahypa",
        "stats_ball":        "⭐ *Jemi bal: {ball}*",
        "stats_rank":        "🎖 Dereje: {rank}",
        "stats_streak":      "🔥 Streak: {streak} gün",
        "stats_time":        "⏰ Wagt: {time}",
        "stats_ball2":       "⭐ Endik baly: {ball}",
        "stats_done":        "✅ Jemi edildi: {n} gezek",
        "stats_missed":      "❌ Jemi edilmedi: {n} gezek",
        "stats_last":        "📅 Soňky: {d}",
        "rating_title":      "🏆 Iň gowy 10",
        "rating_empty":      "Entek hiç kim bal ýygnamandy.",
        "sub_required":      "⚠️ Boty ulanmak üçin kanala agza boluň!",
        "btn_join":          "📢 Kanala geç",
        "btn_joined":        "✅ Agza boldum",
        "invalid_msg":       "⚠️ Näbelli habar, goldanmaýar.",
        "nav_prev":          "⬅️ {n}-sahypa",
        "nav_next":          "{n}-sahypa ➡️",
        "ranks":             ["🌱 Täze başlaýan","🥉 Başlangyç","🥈 Tejribeli","🥇 Hünärmen","💎 Usta","🏆 Rowaýat"],
        "btn_settings":      "⚙️ Sazlamalar",
        "settings_title":    "⚙️ *Sazlamalar*",
        "btn_change_lang":   "🌐 Dili üýtgetmek",
        "btn_change_info":   "📝 Maglumaty üýtgetmek",
        "change_info_text":  "📝 *Maglumaty üýtgetmek*\n\nNäme üýtgetmek isleýärsiňiz?",
        "rating_no_link":    "username ýok",
        "hint_toggle":       "Düwmelere basyp hem endiki tassyklap bilersiňiz!",
        "done_percent":      "*Edildi:* {p}%",
        "share_phone":       "📱 Telefon belgisini paýlaş",
        "ask_phone":         "📱 Telefon belgiňizi iberiň:\n\n_Mysal: +998901234567_",
    },
    "ky": {
        "choose_lang":       "🌐 Тилди тандаңыз:",
        "lang_set":          "✅ Тил өзгөртүлдү!",
        "welcome_new":       "👋 Салам, *{name}*!\n\n🌱 *Адат трекер ботуна* кош келиңиз!\n\nБул бот сизге:\n• Адаттарды белгилөө\n• Убагында эстетме алуу\n• Статистиканы жүргүзүү\nмүмкүнчүлүгүн берет.\n\n*➕ Адат кошуу* баскычын басыңыз!",
        "welcome_back":      "📊 *АДАТТАРЫҢЫЗ:*",
        "btn_add":           "➕ Адат кошуу",
        "btn_delete":        "🗑 Жою",
        "btn_stats":         "📊 Статистика",
        "btn_rating":        "🏆 Рейтинг",
        "btn_home":          "🏠 Башкы меню",
        "btn_cancel":        "❌ Жокко чыгаруу",
        "btn_yes":           "Ооба ✅",
        "btn_no":            "Жок ❌",
        "ask_habit_name":    "📝 Адаттын атын жазыңыз:\n\n_Мисалы: Китеп окуу, Спорт, Суу ичүү..._",
        "ask_habit_time":    "*✅ Адат:* {name}\n\n*⏰ Эстетме убагын киргизиңиз* (24 саат):\n\n_Мисалы: 07:30 же 21:00_",
        "habit_added":       "🎉 *{name}* адаты кошулду!\n\n⏰ Эстетме: *{time}*\n🔥 Streak: 0 күн\n\nКүн сайын аткарыңыз!",
        "wrong_time":        "❌ Туура эмес формат. СС:ММ форматында жазыңыз.\n_Мисалы: 08:00_",
        "no_habits":         "📭 Азырынча адат жок.\n\n➕ Адат кошуңуз!",
        "no_stats":          "📭 Азырынча адат жок.",
        "confirm_delete":    "⚠️ *{name}* адатын чындап жоюуну каалайсызбы?",
        "deleted":           "🗑 *{name}* жойулду.",
        "no_delete":         "📭 Жоюу үчүн адат жок.",
        "done_today":        "✅ Бүгүн буга чейин аткарылды!",
        "done_ok":           "*✅ {name}* — аткарылды!",
        "undone":            "*❌ {name}* — жокко чыгарылды!",
        "all_done":          "Бүгүнкү бардык адатты аткардыңыз, куттуктайбыз 🎉",
        "limit":             "⚠️ Максималдуу 15 адат!",
        "remind_title":      "⏰ *Эстетме!*\n\n🎯 Адат: *{name}*\n\n{motiv}",
        "btn_done":          "✅ Аткардым!",
        "btn_skip":          "❌ Аткарган жокмун",
        "stats_title":       "📊 *Статистика* — {page}/{total} барак",
        "stats_ball":        "⭐ *Жалпы упай: {ball}*",
        "stats_rank":        "🎖 Деңгээл: {rank}",
        "stats_streak":      "🔥 Streak: {streak} күн",
        "stats_time":        "⏰ Убакыт: {time}",
        "stats_ball2":       "⭐ Адат упайы: {ball}",
        "stats_done":        "✅ Жалпы аткарылды: {n} жолу",
        "stats_missed":      "❌ Жалпы өткөрүлдү: {n} жолу",
        "stats_last":        "📅 Акыркы: {d}",
        "rating_title":      "🏆 Топ 10",
        "rating_empty":      "Азырынча эч ким упай чогулткан жок.",
        "sub_required":      "⚠️ Ботту колдонуу үчүн каналга жазылыңыз!",
        "btn_join":          "📢 Каналга өтүү",
        "btn_joined":        "✅ Жазылдым",
        "invalid_msg":       "⚠️ Белгисиз билдирүү, колдоого алынбайт.",
        "nav_prev":          "⬅️ {n}-барак",
        "nav_next":          "{n}-барак ➡️",
        "ranks":             ["🌱 Жаңы баштоочу","🥉 Башталгыч","🥈 Тажрыйбалуу","🥇 Профессионал","💎 Чебер","🏆 Легенда"],
        "btn_settings":      "⚙️ Жөндөөлөр",
        "settings_title":    "⚙️ *Жөндөөлөр*",
        "btn_change_lang":   "🌐 Тилди өзгөртүү",
        "btn_change_info":   "📝 Маалыматты өзгөртүү",
        "change_info_text":  "📝 *Маалыматты өзгөртүү*\n\nЭмнени өзгөрткүңүз келет?",
        "rating_no_link":    "username жок",
        "hint_toggle":       "Баскычтарды басуу аркылуу да адатты ырастасаңыз болот!",
        "done_percent":      "*Аткарылды:* {p}%",
        "share_phone":       "📱 Телефон номерин жөнөт",
        "ask_phone":         "📱 Телефон номериңизди жөнөтүңүз:\n\n_Мисалы: +998901234567_",
    },
    "de": {
        "choose_lang":       "🌐 Sprache wählen:",
        "lang_set":          "✅ Sprache geändert!",
        "welcome_new":       "👋 Hallo, *{name}*!\n\n🌱 Willkommen beim *Gewohnheits-Tracker-Bot*!\n\nDieser Bot hilft dir:\n• Gewohnheiten verfolgen\n• Erinnerungen erhalten\n• Statistiken führen\n\nDrücke *➕ Gewohnheit hinzufügen*!",
        "welcome_back":      "📊 *DEINE GEWOHNHEITEN:*",
        "btn_add":           "➕ Hinzufügen",
        "btn_delete":        "🗑 Löschen",
        "btn_stats":         "📊 Statistik",
        "btn_rating":        "🏆 Rangliste",
        "btn_home":          "🏠 Hauptmenü",
        "btn_cancel":        "❌ Abbrechen",
        "btn_yes":           "Ja ✅",
        "btn_no":            "Nein ❌",
        "ask_habit_name":    "📝 Gewohnheitsname eingeben:\n\n_Beispiel: Lesen, Sport, Wasser trinken..._",
        "ask_habit_time":    "*✅ Gewohnheit:* {name}\n\n*⏰ Erinnerungszeit eingeben* (24h):\n\n_Beispiel: 07:30 oder 21:00_",
        "habit_added":       "🎉 Gewohnheit *{name}* hinzugefügt!\n\n⏰ Erinnerung: *{time}*\n🔥 Serie: 0 Tage\n\nTäglich ausführen!",
        "wrong_time":        "❌ Falsches Format. Bitte HH:MM verwenden.\n_Beispiel: 08:00_",
        "no_habits":         "📭 Noch keine Gewohnheiten.\n\n➕ Füge eine hinzu!",
        "no_stats":          "📭 Noch keine Gewohnheiten.",
        "confirm_delete":    "⚠️ Gewohnheit *{name}* wirklich löschen?",
        "deleted":           "🗑 *{name}* gelöscht.",
        "no_delete":         "📭 Keine Gewohnheit zum Löschen.",
        "done_today":        "✅ Heute bereits erledigt!",
        "done_ok":           "*✅ {name}* — erledigt!",
        "undone":            "*❌ {name}* — rückgängig!",
        "all_done":          "Alle heutigen Gewohnheiten erledigt, Glückwunsch 🎉",
        "limit":             "⚠️ Maximal 15 Gewohnheiten!",
        "remind_title":      "⏰ *Erinnerung!*\n\n🎯 Gewohnheit: *{name}*\n\n{motiv}",
        "btn_done":          "✅ Erledigt!",
        "btn_skip":          "❌ Nicht erledigt",
        "stats_title":       "📊 *Statistik* — Seite {page}/{total}",
        "stats_ball":        "⭐ *Gesamtpunkte: {ball}*",
        "stats_rank":        "🎖 Level: {rank}",
        "stats_streak":      "🔥 Serie: {streak} Tage",
        "stats_time":        "⏰ Zeit: {time}",
        "stats_ball2":       "⭐ Gewohnheitspunkte: {ball}",
        "stats_done":        "✅ Gesamt erledigt: {n} Mal",
        "stats_missed":      "❌ Gesamt verpasst: {n} Mal",
        "stats_last":        "📅 Letztes: {d}",
        "rating_title":      "🏆 Top 10",
        "rating_empty":      "Noch niemand hat Punkte gesammelt.",
        "sub_required":      "⚠️ Abonniere den Kanal um den Bot zu nutzen!",
        "btn_join":          "📢 Zum Kanal",
        "btn_joined":        "✅ Abonniert",
        "invalid_msg":       "⚠️ Unbekannte Nachricht, nicht unterstützt.",
        "nav_prev":          "⬅️ Seite {n}",
        "nav_next":          "Seite {n} ➡️",
        "ranks":             ["🌱 Anfänger","🥉 Einsteiger","🥈 Erfahren","🥇 Profi","💎 Meister","🏆 Legende"],
        "btn_settings":      "⚙️ Einstellungen",
        "settings_title":    "⚙️ *Einstellungen*",
        "btn_change_lang":   "🌐 Sprache ändern",
        "btn_change_info":   "📝 Profil bearbeiten",
        "change_info_text":  "📝 *Profil bearbeiten*\n\nWas möchten Sie ändern?",
        "rating_no_link":    "kein username",
        "hint_toggle":       "Sie können Gewohnheiten auch per Schaltfläche bestätigen!",
        "done_percent":      "*Erledigt:* {p}%",
        "share_phone":       "📱 Telefonnummer senden",
        "ask_phone":         "📱 Senden Sie Ihre Telefonnummer:\n\n_Beispiel: +998901234567_",
    },
    "fr": {
        "choose_lang":       "🌐 Choisissez la langue:",
        "lang_set":          "✅ Langue modifiée!",
        "welcome_new":       "👋 Bonjour, *{name}*!\n\n🌱 Bienvenue sur le *Bot de suivi des habitudes*!\n\nCe bot vous aide à:\n• Définir des habitudes\n• Recevoir des rappels\n• Suivre vos statistiques\n\nAppuyez sur *➕ Ajouter une habitude*!",
        "welcome_back":      "📊 *VOS HABITUDES:*",
        "btn_add":           "➕ Ajouter",
        "btn_delete":        "🗑 Supprimer",
        "btn_stats":         "📊 Statistiques",
        "btn_rating":        "🏆 Classement",
        "btn_home":          "🏠 Menu principal",
        "btn_cancel":        "❌ Annuler",
        "btn_yes":           "Oui ✅",
        "btn_no":            "Non ❌",
        "ask_habit_name":    "📝 Entrez le nom de l'habitude:\n\n_Exemple: Lecture, Sport, Boire de l'eau..._",
        "ask_habit_time":    "*✅ Habitude:* {name}\n\n*⏰ Entrez l'heure du rappel* (24h):\n\n_Exemple: 07:30 ou 21:00_",
        "habit_added":       "🎉 Habitude *{name}* ajoutée!\n\n⏰ Rappel: *{time}*\n🔥 Série: 0 jours\n\nFaites-le chaque jour!",
        "wrong_time":        "❌ Format incorrect. Utilisez HH:MM.\n_Exemple: 08:00_",
        "no_habits":         "📭 Pas encore d'habitudes.\n\nAppuyez sur ➕ Ajouter!",
        "no_stats":          "📭 Pas encore d'habitudes.",
        "confirm_delete":    "⚠️ Supprimer l'habitude *{name}*?",
        "deleted":           "🗑 *{name}* supprimée.",
        "no_delete":         "📭 Aucune habitude à supprimer.",
        "done_today":        "✅ Déjà fait aujourd'hui!",
        "done_ok":           "*✅ {name}* — fait!",
        "undone":            "*❌ {name}* — annulé!",
        "all_done":          "Toutes les habitudes du jour accomplies, félicitations 🎉",
        "limit":             "⚠️ Maximum 15 habitudes!",
        "remind_title":      "⏰ *Rappel!*\n\n🎯 Habitude: *{name}*\n\n{motiv}",
        "btn_done":          "✅ Fait!",
        "btn_skip":          "❌ Non fait",
        "stats_title":       "📊 *Statistiques* — page {page}/{total}",
        "stats_ball":        "⭐ *Total points: {ball}*",
        "stats_rank":        "🎖 Niveau: {rank}",
        "stats_streak":      "🔥 Série: {streak} jours",
        "stats_time":        "⏰ Heure: {time}",
        "stats_ball2":       "⭐ Points habitude: {ball}",
        "stats_done":        "✅ Total accompli: {n} fois",
        "stats_missed":      "❌ Total manqué: {n} fois",
        "stats_last":        "📅 Dernier: {d}",
        "rating_title":      "🏆 Top 10",
        "rating_empty":      "Personne n'a encore marqué de points.",
        "sub_required":      "⚠️ Abonnez-vous à la chaîne pour utiliser le bot!",
        "btn_join":          "📢 Aller à la chaîne",
        "btn_joined":        "✅ Abonné",
        "invalid_msg":       "⚠️ Message inconnu, non supporté.",
        "nav_prev":          "⬅️ Page {n}",
        "nav_next":          "Page {n} ➡️",
        "ranks":             ["🌱 Débutant","🥉 Novice","🥈 Expérimenté","🥇 Professionnel","💎 Maître","🏆 Légende"],
        "btn_settings":      "⚙️ Paramètres",
        "settings_title":    "⚙️ *Paramètres*",
        "btn_change_lang":   "🌐 Changer la langue",
        "btn_change_info":   "📝 Modifier le profil",
        "change_info_text":  "📝 *Modifier le profil*\n\nQue souhaitez-vous modifier?",
        "rating_no_link":    "pas de username",
        "hint_toggle":       "Vous pouvez aussi confirmer les habitudes en appuyant sur les boutons!",
        "done_percent":      "*Accompli:* {p}%",
        "share_phone":       "📱 Envoyer le numéro de téléphone",
        "ask_phone":         "📱 Envoyez votre numéro de téléphone:\n\n_Exemple: +998901234567_",
    },
}


def get_lang(uid):
    u = load_user(uid)
    return u.get("lang", "uz")

def today_uz5():
    """UTC+5 (Toshkent) bo'yicha bugungi sana"""
    from datetime import timezone, timedelta
    tz_uz = timezone(timedelta(hours=5))
    return datetime.now(tz_uz).strftime("%Y-%m-%d")

def T(uid, key, **kwargs):
    lang = get_lang(uid)
    text = LANGS.get(lang, LANGS["uz"]).get(key, LANGS["uz"].get(key, key))
    return text.format(**kwargs) if kwargs else text

def get_rank(uid, points):
    lang   = get_lang(uid)
    ranks  = LANGS.get(lang, LANGS["uz"])["ranks"]
    if points >= 500: rank = ranks[5]
    elif points >= 200: rank = ranks[4]
    elif points >= 100: rank = ranks[3]
    elif points >= 50:  rank = ranks[2]
    elif points >= 20:  rank = ranks[1]
    else: rank = ranks[0]
    # VIP nishon
    u = load_user(uid)
    if u.get("is_vip"):
        rank = "💎 VIP | " + rank
    return rank

def lang_keyboard():
    kb = InlineKeyboardMarkup()
    kb.row(
        InlineKeyboardButton("🇺🇿 O'zbek",   callback_data="set_lang_uz"),
        InlineKeyboardButton("🇬🇧 English",  callback_data="set_lang_en"),
    )
    kb.row(
        InlineKeyboardButton("🇷🇺 Русский",  callback_data="set_lang_ru"),
    )
    return kb

