#!/usr/bin/env python3
"""
Ko'p til - LANGS dictionary
"""

LANGS = {
    "uz": {
        "choose_lang":       "🌐 Tilni tanlang:",
        "lang_set":          "✅ Til o'zgartirildi!",
        "welcome_new":       "👋 Salom, *{name}*!\n\n🌱 *Odatlar Shakllantirish Boti*ga xush kelibsiz!\n\nBu bot sizga:\n• Odatlarni belgilash\n• Vaqtida eslatma olish\n• Streak va statistika kuzatish\nimkonini beradi.\n\nBoshlash uchun *➕ Odat qo'shish* tugmasini bosing!",
        "welcome_back":      "📊 *ODATLARINGIZ:*",
        "btn_add":           "➕ Odat qo'shish",
        "btn_delete":        "🗑 Odatni o'chirish",
        "btn_stats":         "📊 Statistika",
        "btn_rating":        "🏆 Reyting",
        "btn_home":          "🏠 Asosiy menyu",
        "btn_enter":         "📃 Kirish",
        "weekly_share_caption": "<b>Natijalaringiz...</b>\n@Super_habits_bot",
        "share_fwd_btn": "📤 Ulashish",
        "share_del_btn": "✅ Tasdiqlash",
        "btn_ack":       "✅ Tushunarli",
        "main_greeting":     "👋 *Assalomu alaykum, {name}!*\n\n🌱 Odatlaringizni barpo etish, rivojlantirish, kuzatib borish, qiziqarli raqobat, oson va tez shakllantirish uchun, eng to'g'ri joydasiz!\n\nUshbu sayohatni boshlash uchun:\n« 📃 *Kirish*» tugmasini bosing! 👇",
        "btn_cancel":        "❌ Bekor qilish",
        "btn_yes":           "Ha ✅",
        "btn_no":            "Yo'q ❌",
        "ask_habit_name":    "📝 Odatning nomini yozing:\n\n_Masalan: Kitob o'qish, Sport, Suv ichish..._",
        "ask_habit_time":    "*✅ Odat:* {name}\n\n*⏰ Eslatma vaqtini yozing* (24 soat):\n\n_Masalan: 07:30 yoki 21:00_",
        "habit_added":       "🎉 *{name}* odati qo'shildi!\n\n*⏰ Eslatma:* {time} da keladi\n*🔥 Streak:* 0 kun\n\nHar kuni vaqtida bajaring!",
        "wrong_time":        "❌ Noto'g'ri format. HH:MM formatida yozing.\n_Masalan: 08:00_",
        "no_habits":         "📭 Hali odat qo'shilmagan.\n\n➕ Odat qo'shish tugmasini bosing!",
        "no_stats":          "📭 Hali odat yo'q.",
        "confirm_delete":    "⚠️ Haqiqatan ham *{name}* odatini o'chirishni xohlaysizmi?",
        "deleted":           "🗑 *{name}* o'chirildi.",
        "no_delete":         "📭 O'chirish uchun odat yo'q.",
        "done_today":        "✅ Bugun allaqachon bajardingiz!",
        "done_ok":           "*✅ {name}* — bajarildi!",
        "undone":            "*❌ {name}* — bekor qilindi!",
        "all_done":          "Bugungi barcha odatni bajardingiz, tabriklaymiz 🎉",
        "limit":             "⚠️ Odatlarni yaratish me'yori 15 ta!",
        "remind_title":      "⏰ *Eslatma!*\n\n*🎯 Odat:* {name}\n\n{motiv}",
        "btn_done":          "✅ Bajardim!",
        "btn_skip":          "❌ Bajarmadim",
        "stats_title":       "*📊 Statistika —* {page}/{total} sahifa",
        "stats_ball":        "*⭐ Jami ball:* {ball} ball",
        "stats_rank":        "*🎖 Daraja:* {rank}",
        "stats_streak":      "*🔥 Streak:* {streak} kun",
        "stats_time":        "*⏰ Vaqt:* {time}",
        "stats_ball2":       "⭐ Odat balli: {ball} ball",
        "stats_done":        "*✅ Jami bajarilgan:* {n} marta",
        "stats_missed":      "*❌ Jami bajarilmagan:* {n} marta",
        "stats_last":        "*📅 Oxirgi:* {d}",
        "rating_title":      "🏆 Top 10 Reyiting",
        "rating_empty":      "Hali hech kim ball to'plamagan.",
        "sub_required":      "⚠️ Botdan foydalanish uchun avvalo kanalga a'zo bo'ling!",
        "btn_join":          "📢 Kanalga o'tish",
        "btn_joined":        "✅ A'zo bo'ldim",
        "invalid_msg":       "⚠️ Sizning noaniq habarlaringiz qo'llab quvvatlanmaydi.",
        "nav_prev":          "⬅️ {n}-sahifa",
        "nav_next":          "{n}-sahifa ➡️",
        "ranks":             ["🌱 Yangi boshlovchi","🥉 Boshlang'ich","🥈 Tajribali","🥇 Professional","💎 Master","🏆 Legenda"],
        "btn_settings":      "⚙️ Sozlamalar",
        "settings_title":    "⚙️ *Muhim sozlamalar qismi.*",
        "btn_change_lang":   "🌐 Tilni o'zgartirish",
        "btn_change_info":   "📝 Ma'lumotlarni o'zgartirish",
        "change_info_text":  "📝 *Ma'lumotlarni o'zgartirish*\n\nNimani o'zgartirmoqchisiz?",
        "rating_no_link":    "username yo'q",
        "hint_toggle":       "Tugmalarni bosish orqali ham odatni tasdiqlashingiz mumkin!",
        "done_percent":      "*Bajarildi:* {p}%",
        "share_phone":       "📱 Telefon raqamni yuborish",
        "ask_phone":         "📱 Telefon raqamingizni yuboring yoki qo'lda kiriting:\n\n_Masalan: +998901234567_",
        "err_wrong_phone":   "⚠️ Noto'g'ri raqam. Masalan: *+998901234567*",
        "err_wrong_count":   "⚠️ Noto'g'ri son. 1 dan 20 gacha raqam kiriting:",
        "err_time_format":   "⚠️ Noto'g'ri format. Masalan: *HH:MM*",
        "err_time_value":    "⚠️ Noto'g'ri vaqt. Masalan: *HH:MM*",
        "habit_type_choose": "📋 *Odat turini tanlang:*\n\n📌 *Oddiy* — kuniga 1 marta\n🔁 *Takrorlanuvchi* — kuniga bir necha marta (masalan: 5 vaqt namoz)",
        "ask_repeat_count":  "🔁 *Takrorlanuvchi odat*\n\nKuniga necha marta bajarasiz?\n_Masalan: 2, 3, 5_",
        "ask_repeat_first_time": "✅ *{name}*\n\n🔁 Bu takrorlanuvchi odat ({count} marta).\n⏰ *1/{count}* — Birinchi vaqtni kiriting:\n_Masalan: 06:00_\n\nYoki vaqtsiz qo'shing:",
        "ask_repeat_next_time":  "⏰ *{current}/{total}* — Keyingi vaqtni kiriting:\n_Masalan: 18:00_",
        "repeat_progress":   "✅ *{name}* — *{done}/{total}* bajarildi!",
        "btn_type_simple":   "📌 Oddiy",
        "btn_type_repeat":   "🔁 Takrorlanuvchi",
        "btn_no_time":       "⏩ Vaqtsiz qo'shish",
        "edit_repeat_info":  "🔁 *{name}* — takror: {count} marta\nJoriy vaqtlar: {times}\n\nYangi vaqtlarni qayta kiriting:",
        "edit_simple_info":  "⏰ *{name}*\nJoriy vaqt: *{time}*",
        "edit_repeat_first": "⏰ *{name}* uchun *1/{count}* yangi vaqtni kiriting:\n\n_Masalan: 06:00_",
        "edit_simple_new":   "⏰ *{name}* uchun yangi vaqtni kiriting:\n\n_Masalan: 07:30_",
        "err_min_chars":     "⚠️ Kamida 2 harf kiriting!",
        "err_positive_num":  "⚠️ Musbat son kiriting!",
        "err_only_digits":   "⚠️ Faqat raqam kiriting!",
        "err_enter_number":  "⚠️ Son kiriting. Masalan: 100 yoki -50",
        "err_user_not_found":"⚠️ Bu ID foydalanuvchi topilmadi.",
        "err_self_transfer": "⚠️ O'zingizga ball yubora olmaysiz!",
        "err_not_enough_pts":"⚠️ Sizda faqat *{points} ball* bor!",
        "err_max_groups":    "⚠️ Siz admin sifatida 3 tadan ko'p guruh yarata olmaysiz.",
        "set_dev_prompt":    "💬 *Dasturchiga habar yozing:*\n\nHabaringizni quyida kiriting:",
        "set_habit_settings":"⚙️ *Odat sozlamalari*",
        "set_all_notime":    "🔕 Barcha odatlar vaqtsiz holatga o'tkazildi!",
        "set_which_time":    "⏰ *Qaysi odatning vaqtini tahrirlash?*",
        "set_habit_notime":  "🔕 Odat vaqtsiz holatga o'tkazildi!",
        "set_edit_times":    "⏰ *Odatlar vaqtini tahrirlash*",
        "set_which_rename":  "✏️ *Qaysi odatning nomini o'zgartirmoqchisiz?*",
        "set_new_name":      "✏️ Yangi ismingizni yozing:",
        "set_all_time_ask":  "⏰ Barcha odatlar uchun umumiy vaqtni kiriting:\n\n_Masalan: 07:00_",
        "ok_time_updated":   "✅ Vaqt yangilandi!",
        "ok_all_times":      "✅ Barcha odatlar vaqti *{time}* ga o'zgartirildi!",
        "ok_name_changed":   "✅ Ism *{name}* ga o'zgartirildi!",
        "ok_habit_renamed":  "✅ Odat nomi *{name}* ga o'zgartirildi!",
        "ok_dev_sent":       "✅ Xabaringiz dasturchiga yuborildi!",
        "ok_transfer":       "✅ *{amount} ball* muvaffaqiyatli yuborildi!\n\n⭐ Qolgan ballingiz: {points}",
        "ok_points_reset":   "✅ Ballaringiz *0 ga* tushirildi.",
        "del_which_habit":   "🗑 *Qaysi odatni o'chirmoqchisiz?*",
        "add_more_habits":   "➕ *Yana odat qo'shing:*",
        "ok_self_deduct":    "✅ *{amount} ball* ayirib tashlandi.\n\n⭐ Qolgan ballingiz: {points}",
        "admin_gave_pts":    "🎁 Admin sizga *{amount} ball* berdi!\n\n⭐ Hisobingiz: {points} ball",
        "admin_reply":       "↩️ *Admin javobi:*\n\n{text}",
        # ── BOZOR (bot callback) ──
        "bozor_title":       "🛒 *Bozor —* bu sizning ballaringiz bilan qilinadigan barcha amallar joyi.\n\n*⭐ Sizning balingiz:* {points} ball\n*👥 Taklif qilganlar:* {ref_count} ta do'st\n*❤️ Jon:* {jon}%\n\n*❤️ Jon sotib olish —* {jon_price} ball evaziga jonni 100% ga tiklash\n*👥 Do'st taklif qilish —* +50 ball (siz), +25 ball (do'st)\n*💸 Ballarni ayirboshlash —* yaqin insoniga ball yuborish\n*🔴 Ballarimni 0 ga tushirish —* barcha ballarni nollash\n*➖ Ballarimdan olib tashlash —* ma'lum miqdorni ayirish",
        "bozor_btn_buy_jon": "❤️ Jon sotib olish ({price} ball)",
        "bozor_btn_referral":"👥 Do'st taklif qilish",
        "bozor_btn_transfer":"💸 Ballarni ayirboshlash",
        "bozor_btn_reset":   "🔴 Ballarimni 0 ga tushirish",
        "bozor_btn_subtract":"➖ Ballarimdan olib tashlash",
        "bozor_jon_high":    "❤️ *Jon sotib olish mumkin emas!*\n\nJon faqat *20% va undan kam* bo'lganda sotib olinadi.\nHozirgi joningiz: *{jon}%*",
        "bozor_jon_no_pts":  "⭐ *Balingiz yetarli emas!*\n\nJon sotib olish uchun *{price} ball* kerak.\nSizda hozir: *{points} ball*\n\nHar kuni odatlarni bajaring — ball to'playsiz! 💪",
        "bozor_jon_ok":      "❤️ *Jon tiklandi!*\n\n{price} ball sarflandi — joningiz *100%* ga qaytdi!\nEndi odatlarni davom ettiring! 💪",
        "bozor_ref_title":   "👥 *Do'st taklif qilish*",
        "bozor_ref_link":    "*🔗 Sizning linkingiz:*\n`{link}`",
        "bozor_ref_stats":   "*👥 Taklif qilganlar:* {count} ta do'st\n*⭐ Yig'ilgan ball:* +{balls}",
        "bozor_ref_reward":  "*🎁 Har bir do'st uchun:*\n• Siz: *+50 ball*\n• Do'stingiz: *+25 ball*",
        "bozor_ref_goals":   "*🏆 Chegara sovg'alari:*",
        "bozor_ref_next":    "*⏳ Keyingi sovg'agacha:* {need} ta do'st qoldi",
        "bozor_ref_all_done":"🏆 *Barcha chegara sovg'alarini oldingiz!*",
        "bozor_ref_copy":    "📋 Havolani nusxalash",
        "bozor_transfer_ask":"💸 *Ballarni ayirboshlash*\n\nBallarni yubormoqchi bo'lgan foydalanuvchining *Telegram ID* sini kiriting:\n\n_ID raqamni foydalanuvchidan so'rang yoki reytingda ko'ring_",
        "bozor_edit_title":  "✏️ *Ballarni tahrirlash*\n\n⭐ Joriy balingiz: *{points} ball*",
        "bozor_edit_sub_btn":"➖ Ballarimdan qanchasini olib tashlash",
        "bozor_reset_warn":  "⚠️ Haqiqatan ham barcha ballaringizni *0 ga* tushirmoqchimisiz?",
        "bozor_reset_yes":   "✅ Ha, 0 ga tushirish",
        "bozor_reset_no":    "❌ Yo'q",
        "bozor_sub_ask":     "➖ *Ballarni olib tashlash*\n\n⭐ Joriy balingiz: *{points} ball*\n\nQancha ball olib tashlansin?",
        "bozor_btn_back":    "⬅️ Orqaga",
        "stars_item_gift_box": "🎁 Sovga qutisi",
        "stars_desc_gift_box": "Tasodifiy mukofot: 100/200/500 ball, streak himoyasi yoki XP Booster",
        "streak_milestone":  "🔥 *Tabriklaymiz!*\n\n*{days} kunlik streak!*\n\nSiz ajoyib yoʻldasiz — davom eting! 💪",
        # ── Shield (streak himoyasi) — bitta umumiy xabar barcha xavfli odatlarga ──
        "shield_risk_title":      "⚠️ *Streakingiz xavf ostida!*",
        "shield_risk_habit_line": "*🔥* {streak} kun — *{name}*",
        "shield_risk_prompt":     "*🛡 Himoyangiz bor* — ishlatinmi?\n_(1 ta himoya barcha odatlarga ishlaydi. Yoʻq desangiz himoya saqlanib qoladi.)_",
        "shield_btn_yes":         "✅ Ha, ishlatish",
        "shield_btn_no":          "❌ Yoʻq, nollansin",
        "shield_used_title":      "🛡 *Streak himoyangiz ishlatildi!*",
        "shield_used_body":       "*🔥 Saqlangan streaklar:* {count} ta odat\n*🛡 Qolgan himoyalar:* {remaining} ta",
        "shield_skipped":         "❌ *Streaklar nollandi.*\n\n🛡 Himoyangiz saqlanib qoldi — keyingi safar ishlatishingiz mumkin!",

        # ── ESLATMALAR (bir martalik) ──
        "rem_notif_title":        "⏰ *Eslatma!*",
        "rem_btn_done":           "✅ Bajardim (+2)",
        "rem_btn_skip":           "❌ O'tkazib yuborish",
        "rem_done_toast":         "🎉 Ajoyib! *+{pts} ball* qo'shildi.",
        "rem_skipped_toast":      "❌ Eslatma o'tkazib yuborildi.",
        "rem_expired":            "⏳ *Eslatma muddati o'tdi.*",
    },
    "en": {
        "choose_lang":       "🌐 Choose language:",
        "lang_set":          "✅ Language changed!",
        "welcome_new":       "👋 Hello, *{name}*!\n\n🌱 Welcome to *Habit Tracker Bot*!\n\nThis bot helps you:\n• Set habits\n• Get timely reminders\n• Track streaks & stats\n\nPress *➕ Add Habit* to start!",
        "welcome_back":      "📊 *YOUR HABITS:*",
        "btn_add":           "➕ Add Habit",
        "btn_delete":        "🗑 Delete Habit",
        "btn_stats":         "📊 Statistics",
        "btn_rating":        "🏆 Leaderboard",
        "btn_home":          "🏠 Main Menu",
        "btn_enter":         "📃 Open",
        "weekly_share_caption": "<b>Your results...</b>\n@Super_habits_bot",
        "share_fwd_btn": "📤 Share",
        "share_del_btn": "✅ Confirm",
        "btn_ack":       "✅ Got it",
        "main_greeting":     "👋 *Hello, {name}!*\n\n🌱 You're in the right place to build, develop and track your habits, compete with friends, and grow every day!\n\nTo start your journey:\nTap the « 📃 *Open*» button! 👇",
        "btn_cancel":        "❌ Cancel",
        "btn_yes":           "Yes ✅",
        "btn_no":            "No ❌",
        "ask_habit_name":    "📝 Enter habit name:\n\n_Example: Reading, Exercise, Drink water..._",
        "ask_habit_time":    "*✅ Habit:* {name}\n\n*⏰ Enter reminder time* (24h):\n\n_Example: 07:30 or 21:00_",
        "habit_added":       "🎉 Habit *{name}* added!\n\n*⏰ Reminder:* {time}\n*🔥 Streak:* 0 days\n\nComplete it daily!",
        "wrong_time":        "❌ Wrong format. Use HH:MM.\n_Example: 08:00_",
        "no_habits":         "📭 No habits yet.\n\nPress ➕ Add Habit!",
        "no_stats":          "📭 No habits yet.",
        "confirm_delete":    "⚠️ Really delete *{name}*?",
        "deleted":           "🗑 *{name}* deleted.",
        "no_delete":         "📭 No habits to delete.",
        "done_today":        "✅ Already done today!",
        "done_ok":           "*✅ {name}* — done!",
        "undone":            "*❌ {name}* — undone!",
        "all_done":          "You completed all today's habits, congratulations 🎉",
        "limit":             "⚠️ Maximum 15 habits allowed!",
        "remind_title":      "⏰ *Reminder!*\n\n*🎯 Habit:* {name}\n\n{motiv}",
        "btn_done":          "✅ Done!",
        "btn_skip":          "❌ Not done",
        "stats_title":       "*📊 Statistics —* page {page}/{total}",
        "stats_ball":        "⭐ *Total points: {ball}*",
        "stats_rank":        "🎖 Rank: {rank}",
        "stats_streak":      "🔥 Streak: {streak} days",
        "stats_time":        "⏰ Time: {time}",
        "stats_ball2":       "⭐ Habit points: {ball}",
        "stats_done":        "✅ Total done: {n} times",
        "stats_missed":      "❌ Total missed: {n} times",
        "stats_last":        "📅 Last: {d}",
        "rating_title":      "🏆 Top 10 Leaderboard",
        "rating_empty":      "Nobody has points yet.",
        "sub_required":      "⚠️ Please join the channel to use the bot!",
        "btn_join":          "📢 Join Channel",
        "btn_joined":        "✅ I joined",
        "invalid_msg":       "⚠️ Unknown message, not supported.",
        "nav_prev":          "⬅️ Page {n}",
        "nav_next":          "Page {n} ➡️",
        "ranks":             ["🌱 Beginner","🥉 Novice","🥈 Experienced","🥇 Professional","💎 Master","🏆 Legend"],
        "btn_settings":      "⚙️ Settings",
        "settings_title":    "⚙️ *Settings*",
        "btn_change_lang":   "🌐 Change Language",
        "btn_change_info":   "📝 Change Profile",
        "change_info_text":  "📝 *Change Profile*\n\nWhat would you like to change?",
        "rating_no_link":    "no username",
        "hint_toggle":       "You can also confirm habits by pressing the buttons!",
        "done_percent":      "*Done:* {p}%",
        "share_phone":       "📱 Share phone number",
        "ask_phone":         "📱 Share your phone number or type it manually:\n\n_Example: +998901234567_",
        "err_wrong_phone":   "⚠️ Wrong number. Example: *+998901234567*",
        "err_wrong_count":   "⚠️ Wrong number. Enter 1 to 20:",
        "err_time_format":   "⚠️ Wrong format. Example: *HH:MM*",
        "err_time_value":    "⚠️ Wrong time. Example: *HH:MM*",
        "habit_type_choose": "📋 *Choose habit type:*\n\n📌 *Simple* — once a day\n🔁 *Repeating* — multiple times a day (e.g. 5 daily prayers)",
        "ask_repeat_count":  "🔁 *Repeating habit*\n\nHow many times per day?\n_Example: 2, 3, 5_",
        "ask_repeat_first_time": "✅ *{name}*\n\n🔁 This is a repeating habit ({count} times).\n⏰ *1/{count}* — Enter the first time:\n_Example: 06:00_\n\nOr add without time:",
        "ask_repeat_next_time":  "⏰ *{current}/{total}* — Enter the next time:\n_Example: 18:00_",
        "repeat_progress":   "✅ *{name}* — *{done}/{total}* completed!",
        "btn_type_simple":   "📌 Simple",
        "btn_type_repeat":   "🔁 Repeating",
        "btn_no_time":       "⏩ Add without time",
        "edit_repeat_info":  "🔁 *{name}* — repeat: {count} times\nCurrent times: {times}\n\nRe-enter new times:",
        "edit_simple_info":  "⏰ *{name}*\nCurrent time: *{time}*",
        "edit_repeat_first": "⏰ Enter *1/{count}* new time for *{name}*:\n\n_Example: 06:00_",
        "edit_simple_new":   "⏰ Enter new time for *{name}*:\n\n_Example: 07:30_",
        "err_min_chars":     "⚠️ Enter at least 2 characters!",
        "err_positive_num":  "⚠️ Enter a positive number!",
        "err_only_digits":   "⚠️ Enter digits only!",
        "err_enter_number":  "⚠️ Enter a number. Example: 100 or -50",
        "err_user_not_found":"⚠️ User with this ID not found.",
        "err_self_transfer": "⚠️ You cannot send points to yourself!",
        "err_not_enough_pts":"⚠️ You only have *{points} points*!",
        "err_max_groups":    "⚠️ You can create a maximum of 3 groups as admin.",
        "set_dev_prompt":    "💬 *Write to the developer:*\n\nType your message below:",
        "set_habit_settings":"⚙️ *Habit settings*",
        "set_all_notime":    "🔕 All habits set to no-time mode!",
        "set_which_time":    "⏰ *Which habit time to edit?*",
        "set_habit_notime":  "🔕 Habit set to no-time mode!",
        "set_edit_times":    "⏰ *Edit habit times*",
        "set_which_rename":  "✏️ *Which habit to rename?*",
        "set_new_name":      "✏️ Enter your new name:",
        "set_all_time_ask":  "⏰ Enter a common time for all habits:\n\n_Example: 07:00_",
        "ok_time_updated":   "✅ Time updated!",
        "ok_all_times":      "✅ All habits time changed to *{time}*!",
        "ok_name_changed":   "✅ Name changed to *{name}*!",
        "ok_habit_renamed":  "✅ Habit renamed to *{name}*!",
        "ok_dev_sent":       "✅ Your message was sent to the developer!",
        "ok_transfer":       "✅ *{amount} points* sent successfully!\n\n⭐ Remaining: {points}",
        "ok_points_reset":   "✅ Your points have been reset to *0*.",
        "del_which_habit":   "🗑 *Which habit to delete?*",
        "add_more_habits":   "➕ *Add another habit:*",
        "ok_self_deduct":    "✅ *{amount} points* deducted.\n\n⭐ Remaining: {points}",
        "admin_gave_pts":    "🎁 Admin gave you *{amount} points*!\n\n⭐ Balance: {points} points",
        "admin_reply":       "↩️ *Admin reply:*\n\n{text}",
        # ── SHOP (bot callback) ──
        "bozor_title":       "🛒 *Shop —* a place for all actions with your points.\n\n*⭐ Your points:* {points} pts\n*👥 Referred:* {ref_count} friends\n*❤️ Life:* {jon}%\n\n*❤️ Buy life —* restore to 100% for {jon_price} pts\n*👥 Invite friends —* +50 pts (you), +25 pts (friend)\n*💸 Transfer points —* send points to someone\n*🔴 Reset my points —* reset all points to 0\n*➖ Deduct from my points —* subtract a specific amount",
        "bozor_btn_buy_jon": "❤️ Buy life ({price} pts)",
        "bozor_btn_referral":"👥 Invite friends",
        "bozor_btn_transfer":"💸 Transfer points",
        "bozor_btn_reset":   "🔴 Reset my points",
        "bozor_btn_subtract":"➖ Deduct from my points",
        "bozor_jon_high":    "❤️ *Cannot buy life!*\n\nLife can only be purchased at *20% or below*.\nYour current life: *{jon}%*",
        "bozor_jon_no_pts":  "⭐ *Not enough points!*\n\nYou need *{price} pts* to buy life.\nYou have: *{points} pts*\n\nComplete habits daily to earn points! 💪",
        "bozor_jon_ok":      "❤️ *Life restored!*\n\n{price} pts spent — your life is back to *100%*!\nKeep going with your habits! 💪",
        "bozor_ref_title":   "👥 *Invite Friends*",
        "bozor_ref_link":    "*🔗 Your link:*\n`{link}`",
        "bozor_ref_stats":   "*👥 Referred:* {count} friends\n*⭐ Earned:* +{balls}",
        "bozor_ref_reward":  "*🎁 For each friend:*\n• You: *+50 pts*\n• Your friend: *+25 pts*",
        "bozor_ref_goals":   "*🏆 Milestone rewards:*",
        "bozor_ref_next":    "*⏳ Next reward:* {need} more friends",
        "bozor_ref_all_done":"🏆 *All milestone rewards unlocked!*",
        "bozor_ref_copy":    "📋 Copy link",
        "bozor_transfer_ask":"💸 *Transfer Points*\n\nEnter the *Telegram ID* of the user you want to send points to:\n\n_Ask the user for their ID or check the leaderboard_",
        "bozor_edit_title":  "✏️ *Edit Points*\n\n⭐ Current points: *{points} pts*",
        "bozor_edit_sub_btn":"➖ Deduct some of my points",
        "bozor_reset_warn":  "⚠️ Are you sure you want to reset all points to *0*?",
        "bozor_reset_yes":   "✅ Yes, reset to 0",
        "bozor_reset_no":    "❌ No",
        "bozor_sub_ask":     "➖ *Deduct Points*\n\n⭐ Current points: *{points} pts*\n\nHow many points to deduct?",
        "bozor_btn_back":    "⬅️ Back",
        "stars_item_gift_box": "🎁 Gift Box",
        "stars_desc_gift_box": "Random reward: 100/200/500 points, streak shield or XP Booster",
        "streak_milestone":  "🔥 *Congrats!*\n\n*{days}-day streak!*\n\nYou're on a great path — keep going! 💪",
        # ── Shield (streak protection) — one combined message for all at-risk habits ──
        "shield_risk_title":      "⚠️ *Your streaks are at risk!*",
        "shield_risk_habit_line": "*🔥* {streak} days — *{name}*",
        "shield_risk_prompt":     "*🛡 You have protection* — use it?\n_(1 shield covers all habits. If you say No, the shield stays.)_",
        "shield_btn_yes":         "✅ Yes, use it",
        "shield_btn_no":          "❌ No, reset",
        "shield_used_title":      "🛡 *Streak shield activated!*",
        "shield_used_body":       "*🔥 Streaks saved:* {count} habit(s)\n*🛡 Shields left:* {remaining}",
        "shield_skipped":         "❌ *Streaks reset.*\n\n🛡 Your shield is saved — you can use it next time!",

        # ── REMINDERS (one-time) ──
        "rem_notif_title":        "⏰ *Reminder!*",
        "rem_btn_done":           "✅ Done (+2)",
        "rem_btn_skip":           "❌ Skip",
        "rem_done_toast":         "🎉 Great! *+{pts} points* added.",
        "rem_skipped_toast":      "❌ Reminder skipped.",
        "rem_expired":            "⏳ *Reminder expired.*",
    },
    "ru": {
        "choose_lang":       "🌐 Выберите язык:",
        "lang_set":          "✅ Язык изменён!",
        "welcome_new":       "👋 Привет, *{name}*!\n\n🌱 Добро пожаловать в *Бот трекер привычек*!\n\nЭтот бот поможет вам:\n• Отслеживать привычки\n• Получать напоминания\n• Вести статистику\n\nНажмите *➕ Добавить привычку*!",
        "welcome_back":      "📊 *ВАШИ ПРИВЫЧКИ:*",
        "btn_add":           "➕ Добавить",
        "btn_delete":        "🗑 Удалить",
        "btn_stats":         "📊 Статистика",
        "btn_rating":        "🏆 Рейтинг",
        "btn_home":          "🏠 Главное меню",
        "btn_enter":         "📃 Войти",
        "weekly_share_caption": "<b>Ваши результаты...</b>\n@Super_habits_bot",
        "share_fwd_btn": "📤 Поделиться",
        "share_del_btn": "✅ Подтвердить",
        "btn_ack":       "✅ Понятно",
        "main_greeting":     "👋 *Здравствуйте, {name}!*\n\n🌱 Вы в правильном месте для создания, развития и отслеживания привычек, соревнований с друзьями и ежедневного роста!\n\nЧтобы начать путешествие:\nНажмите кнопку « 📃 *Войти*»! 👇",
        "btn_cancel":        "❌ Отмена",
        "btn_yes":           "Да ✅",
        "btn_no":            "Нет ❌",
        "ask_habit_name":    "📝 Введите название привычки:\n\n_Пример: Чтение, Спорт, Вода..._",
        "ask_habit_time":    "*✅ Привычка:* {name}\n\n*⏰ Введите время* (24ч):\n\n_Пример: 07:30 или 21:00_",
        "habit_added":       "🎉 Привычка *{name}* добавлена!\n\n*⏰ Напоминание:* {time}\n*🔥 Серия:* 0 дней\n\nВыполняйте каждый день!",
        "wrong_time":        "❌ Неверный формат. Используйте ЧЧ:ММ.\n_Пример: 08:00_",
        "no_habits":         "📭 Привычек пока нет.\n\nНажмите ➕ Добавить!",
        "no_stats":          "📭 Привычек пока нет.",
        "confirm_delete":    "⚠️ Удалить привычку *{name}*?",
        "deleted":           "🗑 *{name}* удалена.",
        "no_delete":         "📭 Нет привычек для удаления.",
        "done_today":        "✅ Уже выполнено сегодня!",
        "done_ok":           "*✅ {name}* — выполнено!",
        "undone":            "*❌ {name}* — отменено!",
        "all_done":          "Вы выполнили все привычки сегодня, поздравляем 🎉",
        "limit":             "⚠️ Максимум 15 привычек!",
        "remind_title":      "⏰ *Напоминание!*\n\n*🎯 Привычка:* {name}\n\n{motiv}",
        "btn_done":          "✅ Выполнено!",
        "btn_skip":          "❌ Не выполнено",
        "stats_title":       "📊 *Статистика* — стр. {page}/{total}",
        "stats_ball":        "⭐ *Всего очков: {ball}*",
        "stats_rank":        "🎖 Уровень: {rank}",
        "stats_streak":      "🔥 Серия: {streak} дней",
        "stats_time":        "⏰ Время: {time}",
        "stats_ball2":       "⭐ Очки за привычку: {ball}",
        "stats_done":        "✅ Всего выполнено: {n} раз",
        "stats_missed":      "❌ Всего пропущено: {n} раз",
        "stats_last":        "📅 Последнее: {d}",
        "rating_title":      "🏆 Топ 10",
        "rating_empty":      "Никто ещё не набрал очков.",
        "sub_required":      "⚠️ Подпишитесь на канал, чтобы использовать бота!",
        "btn_join":          "📢 Перейти на канал",
        "btn_joined":        "✅ Я подписался",
        "invalid_msg":       "⚠️ Неизвестное сообщение, не поддерживается.",
        "nav_prev":          "⬅️ Стр. {n}",
        "nav_next":          "Стр. {n} ➡️",
        "ranks":             ["🌱 Новичок","🥉 Начинающий","🥈 Опытный","🥇 Профессионал","💎 Мастер","🏆 Легенда"],
        "btn_settings":      "⚙️ Настройки",
        "settings_title":    "⚙️ *Настройки*",
        "btn_change_lang":   "🌐 Изменить язык",
        "btn_change_info":   "📝 Изменить профиль",
        "change_info_text":  "📝 *Изменить профиль*\n\nЧто хотите изменить?",
        "rating_no_link":    "нет username",
        "hint_toggle":       "Вы также можете подтверждать привычки нажатием кнопок!",
        "done_percent":      "*Выполнено:* {p}%",
        "share_phone":       "📱 Отправить номер телефона",
        "ask_phone":         "📱 Отправьте номер телефона или введите вручную:\n\n_Пример: +998901234567_",
        "err_wrong_phone":   "⚠️ Неверный номер. Пример: *+998901234567*",
        "err_wrong_count":   "⚠️ Неверное число. Введите от 1 до 20:",
        "err_time_format":   "⚠️ Неверный формат. Пример: *ЧЧ:ММ*",
        "err_time_value":    "⚠️ Неверное время. Пример: *ЧЧ:ММ*",
        "habit_type_choose": "📋 *Выберите тип привычки:*\n\n📌 *Обычная* — раз в день\n🔁 *Повторяющаяся* — несколько раз в день (напр. 5 намазов)",
        "ask_repeat_count":  "🔁 *Повторяющаяся привычка*\n\nСколько раз в день?\n_Пример: 2, 3, 5_",
        "ask_repeat_first_time": "✅ *{name}*\n\n🔁 Это повторяющаяся привычка ({count} раз).\n⏰ *1/{count}* — Введите первое время:\n_Пример: 06:00_\n\nИли добавьте без времени:",
        "ask_repeat_next_time":  "⏰ *{current}/{total}* — Введите следующее время:\n_Пример: 18:00_",
        "repeat_progress":   "✅ *{name}* — *{done}/{total}* выполнено!",
        "btn_type_simple":   "📌 Обычная",
        "btn_type_repeat":   "🔁 Повторяющаяся",
        "btn_no_time":       "⏩ Добавить без времени",
        "edit_repeat_info":  "🔁 *{name}* — повтор: {count} раз\nТекущее время: {times}\n\nВведите новое время заново:",
        "edit_simple_info":  "⏰ *{name}*\nТекущее время: *{time}*",
        "edit_repeat_first": "⏰ Введите *1/{count}* новое время для *{name}*:\n\n_Пример: 06:00_",
        "edit_simple_new":   "⏰ Введите новое время для *{name}*:\n\n_Пример: 07:30_",
        "err_min_chars":     "⚠️ Введите минимум 2 символа!",
        "err_positive_num":  "⚠️ Введите положительное число!",
        "err_only_digits":   "⚠️ Введите только цифры!",
        "err_enter_number":  "⚠️ Введите число. Пример: 100 или -50",
        "err_user_not_found":"⚠️ Пользователь с таким ID не найден.",
        "err_self_transfer": "⚠️ Нельзя отправить баллы самому себе!",
        "err_not_enough_pts":"⚠️ У вас только *{points} баллов*!",
        "err_max_groups":    "⚠️ Как админ вы можете создать максимум 3 группы.",
        "set_dev_prompt":    "💬 *Напишите разработчику:*\n\nВведите сообщение ниже:",
        "set_habit_settings":"⚙️ *Настройки привычек*",
        "set_all_notime":    "🔕 Все привычки переведены в режим без времени!",
        "set_which_time":    "⏰ *Время какой привычки изменить?*",
        "set_habit_notime":  "🔕 Привычка переведена в режим без времени!",
        "set_edit_times":    "⏰ *Редактировать время привычек*",
        "set_which_rename":  "✏️ *Какую привычку переименовать?*",
        "set_new_name":      "✏️ Введите новое имя:",
        "set_all_time_ask":  "⏰ Введите общее время для всех привычек:\n\n_Пример: 07:00_",
        "ok_time_updated":   "✅ Время обновлено!",
        "ok_all_times":      "✅ Время всех привычек изменено на *{time}*!",
        "ok_name_changed":   "✅ Имя изменено на *{name}*!",
        "ok_habit_renamed":  "✅ Привычка переименована в *{name}*!",
        "ok_dev_sent":       "✅ Сообщение отправлено разработчику!",
        "ok_transfer":       "✅ *{amount} баллов* успешно отправлено!\n\n⭐ Остаток: {points}",
        "ok_points_reset":   "✅ Ваши баллы сброшены до *0*.",
        "del_which_habit":   "🗑 *Какую привычку удалить?*",
        "add_more_habits":   "➕ *Добавьте ещё привычку:*",
        "ok_self_deduct":    "✅ *{amount} баллов* списано.\n\n⭐ Остаток: {points}",
        "admin_gave_pts":    "🎁 Админ начислил вам *{amount} баллов*!\n\n⭐ Баланс: {points} баллов",
        "admin_reply":       "↩️ *Ответ админа:*\n\n{text}",
        # ── МАГАЗИН (bot callback) ──
        "bozor_title":       "🛒 *Магазин —* место для всех действий с вашими баллами.\n\n*⭐ Ваши баллы:* {points} б.\n*👥 Приглашено:* {ref_count} друзей\n*❤️ Жизнь:* {jon}%\n\n*❤️ Купить жизнь —* восстановить до 100% за {jon_price} б.\n*👥 Пригласить друзей —* +50 б. (вам), +25 б. (другу)\n*💸 Перевести баллы —* отправить баллы кому-то\n*🔴 Сбросить баллы —* обнулить все баллы\n*➖ Списать баллы —* вычесть определённую сумму",
        "bozor_btn_buy_jon": "❤️ Купить жизнь ({price} б.)",
        "bozor_btn_referral":"👥 Пригласить друзей",
        "bozor_btn_transfer":"💸 Перевести баллы",
        "bozor_btn_reset":   "🔴 Сбросить мои баллы",
        "bozor_btn_subtract":"➖ Списать баллы",
        "bozor_jon_high":    "❤️ *Невозможно купить жизнь!*\n\nЖизнь можно купить только при *20% и ниже*.\nВаша жизнь сейчас: *{jon}%*",
        "bozor_jon_no_pts":  "⭐ *Недостаточно баллов!*\n\nДля покупки жизни нужно *{price} б.*\nУ вас: *{points} б.*\n\nВыполняйте привычки — копите баллы! 💪",
        "bozor_jon_ok":      "❤️ *Жизнь восстановлена!*\n\n{price} б. потрачено — жизнь снова *100%*!\nПродолжайте выполнять привычки! 💪",
        "bozor_ref_title":   "👥 *Пригласить друзей*",
        "bozor_ref_link":    "*🔗 Ваша ссылка:*\n`{link}`",
        "bozor_ref_stats":   "*👥 Приглашено:* {count} друзей\n*⭐ Заработано:* +{balls}",
        "bozor_ref_reward":  "*🎁 За каждого друга:*\n• Вам: *+50 б.*\n• Другу: *+25 б.*",
        "bozor_ref_goals":   "*🏆 Бонусы за вехи:*",
        "bozor_ref_next":    "*⏳ До следующего бонуса:* ещё {need} друзей",
        "bozor_ref_all_done":"🏆 *Все бонусы за вехи получены!*",
        "bozor_ref_copy":    "📋 Скопировать ссылку",
        "bozor_transfer_ask":"💸 *Перевод баллов*\n\nВведите *Telegram ID* пользователя, которому хотите отправить баллы:\n\n_Спросите ID у пользователя или посмотрите в рейтинге_",
        "bozor_edit_title":  "✏️ *Редактирование баллов*\n\n⭐ Текущие баллы: *{points} б.*",
        "bozor_edit_sub_btn":"➖ Списать часть баллов",
        "bozor_reset_warn":  "⚠️ Вы уверены, что хотите сбросить все баллы до *0*?",
        "bozor_reset_yes":   "✅ Да, сбросить",
        "bozor_reset_no":    "❌ Нет",
        "bozor_sub_ask":     "➖ *Списание баллов*\n\n⭐ Текущие баллы: *{points} б.*\n\nСколько баллов списать?",
        "bozor_btn_back":    "⬅️ Назад",
        "stars_item_gift_box": "🎁 Подарочная коробка",
        "stars_desc_gift_box": "Случайная награда: 100/200/500 очков, защита стрика или XP Бустер",
        "streak_milestone":  "🔥 *Поздравляем!*\n\n*Streak {days} дней!*\n\nВы на отличном пути — продолжайте! 💪",
        # ── Shield (защита стрика) — одно общее сообщение для всех привычек под угрозой ──
        "shield_risk_title":      "⚠️ *Ваш стрик под угрозой!*",
        "shield_risk_habit_line": "*🔥* {streak} дн. — *{name}*",
        "shield_risk_prompt":     "*🛡 У вас есть защита* — использовать?\n_(1 защита покрывает все привычки. Если нет — защита сохранится.)_",
        "shield_btn_yes":         "✅ Да, использовать",
        "shield_btn_no":          "❌ Нет, обнулить",
        "shield_used_title":      "🛡 *Защита стрика активирована!*",
        "shield_used_body":       "*🔥 Сохранено стриков:* {count} привычек\n*🛡 Осталось защит:* {remaining}",
        "shield_skipped":         "❌ *Стрики обнулены.*\n\n🛡 Защита сохранилась — используйте её в следующий раз!",

        # ── НАПОМИНАНИЯ (одноразовые) ──
        "rem_notif_title":        "⏰ *Напоминание!*",
        "rem_btn_done":           "✅ Выполнил (+2)",
        "rem_btn_skip":           "❌ Пропустить",
        "rem_done_toast":         "🎉 Отлично! *+{pts} баллов* добавлено.",
        "rem_skipped_toast":      "❌ Напоминание пропущено.",
        "rem_expired":            "⏳ *Срок напоминания истёк.*",
    },
}



